kubernetes-sigs/cluster-api-provider-gcp

.gitignore
**What this PR does / why we need it**: Updates .gitignore.
Fixes #
```release-note
NONE
```
=> Ignore files created by IntelliJ IDEA / GoLand.

.github/PULL_REQUEST_TEMPLATE.md
Copied from https://github.com/kubernetes-sigs/clustersapi/blob/master/.github/PULL_REQUEST_TEMPLATE.md
Fixes #
```release-note
NONE
```
=> Set a PR template to use in this repository

Gopkg.lock
**What this PR does / why we need it**: 
Fixes #
**Special notes for your reviewer**: _n/a_
```release-note
NONE
```
=> Update dependencies running `dep ensure`.

cmd/gce-controller/main.go
It's a little cleaner than exiting with success
```release-note
NONE
```
=> Exit from main with exit code 1 on error

.github/PULL_REQUEST_TEMPLATE.md
Fixes #
```release-note
NONE
```
=> Update links in the pull request template.

README.md
Fixes #
```release-note
NONE
```
=> Remove the note about using an old, vulnerable version of minikube.

.gitignore
Fixes #
```release-note
NONE
```
=> .gitignore: Add some temp files

Dockerfile, cmd/clusterctl/examples/google/machine_setup_configs.yaml, cmd/clusterctl/examples/google/provider-components.yaml.template, pkg/cloud/google/machineactuator.go, scripts/fetch_ext_bins.sh
Otherwise we fail silently, for example on a 404.
```release-note
NONE
```
=> Add -f (--fail) flag to all curl invocations

pkg/cloud/google/clients/errors/errors.go, pkg/cloud/google/clients/token_source.go, pkg/cloud/google/serviceaccount.go, pkg/controller/add_cluster.go, pkg/controller/add_machine.go
=> Boilerplate & a few typo fixes

cmd/clusterctl/main.go, cmd/manager/main.go
**What this PR does / why we need it**: Without this change, pretty much all log output gets swallowed, making it extremely difficult to do any debugging. 
Fixes #
**Special notes for your reviewer**: This is essentially a copy of https://github.com/kubernetes-sigs/cluster-api-provider-aws/pull/421 for this repo (thanks @vincepri!). 
```release-note
NONE
```
/assign @justinsb
=> Fix log output, now that the cluster-api has switched to klog.

cmd/clusterctl/examples/google/machine_setup_configs.yaml
Attempt to patch up docker version and make consistent between ControlPlane and Nodes
```release-note
NONE
```
=> Attempt to patch up docker version and make consistent between ControlPlane and Nodes

README.md
Current prerequisites section doesn't have the step to install GO. So included a step in prerequisite section to install go
Fixes #
```release-note
```
=> Update Readme to include go installation

pkg/cloud/google/machineactuator.go
=> Implement UpdateStatus for error reporting

cmd/manager/main.go
panic is generally a code-smell, IMO.
```release-note
NONE
```
=> Refactor initStaticDeps to return an error instead of panic

README.md
Signed-off-by: alejandrox1 <alarcj137@gmail.com>
This fixes a link in the README.
```release-note
NONE
```
=> Fixed cluster-api link

Makefile, cloudbuild.yaml
=>  ✨Add prow image push

config/default/manager_image_patch.yaml
Removes my personal project and adds the new prow staging images
Fixes #
/assign @detiber
=> :running: Point to correct image in kustomize patch

cloud/scope/clients.go, main.go
=> 🐛 Fix event recorder name

controllers/gcpmachine_controller.go
Change-Id: Id06a4f2a44d6aa5cd9534bf63ba2c200d27c45ac
Fixes #154
=> Reconcile Loadbalancers when we update instance group

cloud/services/compute/loadbalancers.go, controllers/gcpcluster_controller.go, controllers/gcpmachine_controller.go, go.sum
=> 🐛 Only watch GCPCluster / reconcile backend services on Machines

cloud/services/compute/instancegroup.go
=> 🐛 Save self link in ReconcileInstanceGroup

cloud/services/compute/loadbalancers.go
=> 🐛 Reconcile instance groups before updating backends

cloud/services/compute/instances.go, go.mod, go.sum, main.go, scripts/ci-e2e.sh
Change-Id: Ifd896b5a6e4f208ce4600613d50f6d80e798ebe1
Fixes #
=> Replace references to AWS

hack/ci/e2e-conformance.sh
=> Better activity log and don't fail when there are no instances

hack/ci/e2e-conformance.sh, hack/heartbeat_account.py, scripts/ci-e2e.sh
=> Clean up ci job - fix nats cleanup / add boskos heartbeat

docs/prerequisites.md
=> :book: Add prerequisites file

hack/ci/e2e-conformance.sh
Change-Id: Ia1afe8e1c39c1127275aa4155467ffa0b4f4cd11
Fixes #
=> add-access-config needs zone info

cloud/services/compute/instances.go
Putting it into its own function is simpler, and we also no longer
need the kubelet version when the image is pre-specified.
Fixes #
=> ✨ Refactor source image computation

api/v1alpha2/gcpmachine_types.go, cloud/services/compute/instances.go, config/crd/bases/infrastructure.cluster.x-k8s.io_gcpmachines.yaml, config/crd/bases/infrastructure.cluster.x-k8s.io_gcpmachinetemplates.yaml
Some small fixes around some AWS-isms.
=> ✨ Tweak some descriptions / comments

scripts/ci-e2e.sh
Looks like boskos.log is empty. let's make sure we append to it.
Fixes #
=> ✨Append to boskos log, no need for nohup

hack/ci/e2e-conformance.sh
=>  ✨ Log activity from when we started the job

hack/ci/e2e-conformance.sh
Currently we exit the loop after just one instance is processed as some
of the commands are greedy and ready the stdin. So store the list of
instances and look up zone for each one of them as we need them.
Change-Id: Ie71d10691088b17fbfea6b3d52de2c5d732f28b3
Fixes #
=>  ✨Fix loop for instances when pulling logs

README.md
=> 📖 Fixup README badges links

Makefile, cloudbuild.yaml
=> 🏃Fixup release Makefile targets

hack/ci/e2e-conformance.sh
Change-Id: I030bde63e997c06eff517204eff8dcec6819f956
Fixes #
=> Tweak how we get the zone info for an instance

hack/ci/e2e-conformance.sh
=> ✨ Simplify travesing the list of instances

examples/generate.sh
=> 🏃 Use released components instead of building

hack/ci/e2e-conformance.sh
Change-Id: I88afd4651df9ecbc9b1ef775ee1033e79e51fe17
Fixes #
=> Fetch more logs - this time from all the GCP nodes

examples/generate.sh
Change-Id: Ibc52aa128e28b422a1d6e53ea1ce5010c96ccf77
Fixes #
=> ✨Add a way to run master branch of capi and cabpk

hack/ci/e2e-conformance.sh
Change-Id: I9fefd19771989a365f220410eb8374b56049848b
Fixes #
=> Option to skip running tests

hack/ci/e2e-conformance.sh
Change-Id: I09326602acee0694594170e5f8e5aef98f88c928
Fixes #
=> ✨Add option to toggle verbosity

docs/conformance.md
=> 📖Add dev oriented doc for the conformance tests

docs/conformance.md, hack/ci/e2e-conformance.sh
Change-Id: I1c536c080d0d1e5df3ec370e5c2ca43fb4461181
Fixes #
=> Add option to cleanup

examples/generate.sh
=> ✨ print version numbers for CAPI and CABPK during generate

Makefile
=> 🏃Verify go mod files and generated files

hack/ci/e2e-conformance.sh
=> ✨Dump info from all the CRDs

examples/generate.sh, hack/ci/e2e-conformance.sh
=> Update kubernetes version to 1.16.1

scripts/ci-e2e.sh
Pass through any arguments, makes it easier to setup the CI jobs
Fixes #
=> ✨ Support the new --use-ci-artifacts for testing against k/k ci builds

examples/controlplane/kustomizeversions.yaml, examples/machinedeployment/kustomizeversions.yaml
=> ✨Clean up bootstrap file

hack/ci/e2e-conformance.sh
=> Add option to reuse images explicitly

config/default/manager_image_patch.yaml
=> :warning: Change manager image to release-0.2

examples/generate.sh, examples/provider-components/kustomization.yaml, examples/provider-components/manager_tolerations_patch.yaml
=> :bug: Default to master branch in generate.sh

Dockerfile, config/default/manager_image_patch.yaml, go.mod, go.sum
=>  🏃 Update Go 1.12.10 and modules

hack/ci/e2e-conformance.sh
=> 🏃Install kustomize under hack/tools, run make modules before build

config/default/manager_image_patch.yaml
=> :bug: Fixup image patch

hack/ci/e2e-conformance.sh
=> :bug: Set PULL_POLICY to Never in CI e2e

examples/machinedeployment/machinedeployment.yaml
=> :bug: Add clusterName to MD template

hack/ci/e2e-conformance.sh
=> 🐛PHASE has upper case letter now - running->Running

hack/ci/e2e-conformance.sh
=> ✨ work with pod utils - fix go/src directory location

hack/ci/e2e-conformance.sh, scripts/ci-e2e.sh
- Add a loop for processing parameters
- pass through parameters via ci-e2e.sh
- better location for boskos logs
Fixes #
=> ✨Fine tune ci-e2e / e2e-conformance.sh

hack/ci/e2e-conformance.sh
=> 🏃Reduce cleanup timeout

Makefile, examples/generate.sh
=> :bug: Fix conformance tests, install cert-manager

examples/controlplane/controlplane.yaml, examples/controlplane/kustomizeversions.yaml, examples/machinedeployment/kustomizeversions.yaml, examples/machinedeployment/machinedeployment.yaml
=> 🐛Update KubeadmConfig(s) to v1alpha3

Makefile, hack/ensure-kind.sh
Related to kubernetes-sigs/cluster-api#1796
=> 🏃 Update to KIND v0.6.1

.dockerignore, .gitignore, tilt-provider.json
=> :sparkles: Add tilt

Makefile
=> Makefile: add missing kustomize dependency

OWNERS_ALIASES
Add myself to cluster-api-gcp-maintainers
=> 🏃 Add gab-satchi to cluster-api-gcp-maintainers

OWNERS_ALIASES
Adds rsmitty to list of maintainers
=> :seedling: add rsmitty to maintainers

hack/ci/e2e-conformance.sh
Update e2e-conformance.sh to use image-builder deps-gce target for installing dependencies
Depends on: https://github.com/kubernetes/test-infra/pull/18531 and an update to the kubekins-e2e image to include the new python3 packages before this will work correctly.
Fixes #
=> Update e2e-conformance.sh to use image-builder deps-gce target for installing dependencies

Makefile, metadata.yaml
Add metadata.yaml for defining contracts, similar we have for the other providers
/cc @wfernandes 
Fixes #
=> ✨ Add metadata.yaml for defining contracts

Makefile, hack/ci/e2e-conformance.sh
This PR fix the conformance job
Fixes https://github.com/kubernetes/kubernetes/issues/95729
=> 🐛 fix conformance job

go.mod, main.go
To make similar to the other providers, this PR refactor the flag parse. this is a small refactor and does not add any new feature
none
=> 🏃 manager: small flags refactor

hack/ci/e2e-conformance.sh
Update worker nodes for conformance test, maybe makes sense when running conformance, i saw in other places that uses at least 5 nodes
also update the variables to match the k8s version we are using
/assing @detiber @rsmitty 
if that makes no sense feel free to close it
Fixes #
=> 🏃 Update worker nodes for conformance test

Makefile
Fixes the link in Makefile that has changed -
```
$ curl -I https://suva.sh/posts/well-documented-makefiles
HTTP/2 301
date: Thu, 05 Nov 2020 19:54:53 GMT
cache-control: max-age=3600
expires: Thu, 05 Nov 2020 20:54:53 GMT
location: https://www.thapaliya.com/posts/well-documented-makefiles
cf-request-id: 063b9301eb00000d3ab18b7000000001
expect-ct: max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"
report-to: {"endpoints":[{"url":"https:\/\/a.nel.cloudflare.com\/report?s=Vm3fJ5IXhTGq%2BERP%2B6vmZfns%2FwbLZu1F6a4c199TV2chg0ccfa42GEMDKHgihr9R8oI77vHHDY%2FeCuDOXKz0ij3BOnmka7%2FD"}],"group":"cf-nel","max_age":604800}
nel: {"report_to":"cf-nel","max_age":604800}
server: cloudflare
cf-ray: 5ed921164a920d3a-ARN
``` …
=> Link in makefile has changed

Makefile, docs/prerequisites.md
Fixes error when creating target cluster using `make create-workload-cluster` for OSX.
Fixes #271
=> Fix calling timeout for osx

docs/releasing.md
=> :running: Add a releasing doc

OWNERS_ALIASES
- add cpanato (myself) to capg maintainers list
- update `cluster-api-maintainers` to match the capi
- order alphabetically
I have two sponsors that reach me to open this PR: @detiber and @rsmitty thanks!
Fixes #
/assign @detiber @vincepri
=> 🏃 Proposal: add cpanato to capg maintainers list

cloud/services/compute/instances.go
This PR fixes subnetwork GCE subnetwork url
Fixes #286
=> Fixing subnetworks url

Makefile, docs/releasing.md
release: update notes and makefile from feedback of release 0.3.0
Fixes #
/assign @detiber
=> 📖 release: update notes and makefile from feedback of release 0.3.0

scripts/ci-e2e.sh
(and not actually run tests)
/kind feature
Fixes #
**TODOs**:
```release-note
NONE
```
=> Option to just build image needed in scripts/ci-e2e.sh

OWNERS_ALIASES
I have been maintaining the CI jobs etc over time, can you please
consider me as a maintainer?
https://github.com/kubernetes-sigs/cluster-api-provider-gcp/graphs/contributors
/kind other
Fixes #
**TODOs**:
```release-note
NONE
```
=> Add dims as maintainer

controllers/gcpcluster_controller.go
/kind feature
This PR implements https://github.com/kubernetes-sigs/cluster-api/blob/master/docs/proposals/20210203-externally-managed-cluster-infrastructure.md for the GCP provider.
```release-note
GCP provider now supports the externally managed annotation as documented here https://github.com/kubernetes-sigs/cluster-api/blob/master/docs/proposals/20210203-externally-managed-cluster-infrastructure.md
```
=> ✨ Add externally managed predicate to GCPCluster controller

docs/releasing.md
small update on the release documentation to reflect the steps made for the release v0.3.1
/assign @detiber @dims 
Fixes #
**TODOs**:
```release-note
NONE
```
=> docs/release: update based on the release v0.3.1

cloud/services/compute/firewalls.go, cloud/services/compute/instancegroup.go, cloud/services/compute/instances.go, cloud/services/compute/loadbalancers.go, cloud/services/compute/network.go, cloud/services/compute/service.go, controllers/gcpmachine_controller.go
To replace PR #346. 
1. Check for ErrNotFound for all Delete requests 
2. Delete gcpmachine finalizer if instance not found 
Fixes #
**TODOs**:
```release-note
NONE
```
=> check ErrNotFound for delete requests, also remove finalizer if VM not found

Makefile, test/e2e/config/gcp-ci.yaml
/kind feature
Using the release CAPI artifacts, the images was not published so that was failing, now it is live and we can use the released artifacts
/assign @dims 
Fixes #
**TODOs**:
```release-note
NONE
```
=> capi: using released artifacts from github

test/e2e/capi_test.go, test/e2e/common.go, test/e2e/config/gcp-ci.yaml
Signed-off-by: Carlos Panato <ctadeu@gmail.com>
Fixes #
**TODOs**:
```release-note
capg: add initial capi tests
```
=> capg: add initial capi tests

Makefile
Looks like we forgot to default!
/kind cleanup
Fixes #
**TODOs**:
```release-note
```
=> Set default for curl retries

.gitignore, Dockerfile, Makefile, Tiltfile, docs/development.md, hack/ensure-go.sh, hack/kustomize-sub.sh, scripts/kind-with-registry.sh, scripts/setup-dev-enviroment.sh, tilt_modules/cert_manager/README.md, tilt_modules/cert_manager/Tiltfile, tilt_modules/cert_manager/test/Tiltfile, tilt_modules/cert_manager/test/test.sh, tilt_modules/extensions.json
/kind feature
dev-workflow: add tilt and documentation to develop capg 
/assign @dims 
Fixes #
**TODOs**:
```release-note
dev-workflow: add tilt and documentation to develop capg 
```
=> dev-workflow: add tilt and documentation to develop capg 

README.md
Fixes #
**TODOs**:
```release-note
None
```
=> 🏃 Fixup README googlecloud icon link

test/e2e/common.go
This PR fixes compiler error `UndeclaredName` in some editor. eg: vscode
**TODOs**:
```release-note
None
```
=> 🏃 Fix compiler UndeclaredName error

docs/development.md
/kind bug
Fix typos in the development doc
/assign @dims 
Fixes #
**TODOs**:
```release-note
NONE
```
=> Fix typos in the development doc

docs/prerequisites.md
This PR elaborates the pre-requisite steps for network creation
Fixes #
**TODOs**:
```release-note
Improved pre-requisite doc
```
=> Add pre-requisites for default network setup

README.md
Fixes #409 
This is just a section of the issue #409 
**TODOs**:
```release-note
NONE
```
=> Added quick start section to readme

README.md
This PR adds a involvement & contribution section for encouraging new contributors
Fixes #
This a part of issue #409 
**TODOs**:
```release-note
NONE
```
=> Added contributing & involvement section

README.md
Modifies the office hour section and updates the slack channel link.
Fixes #
Fixes a part of #409 
**TODOs**:
```release-note
NONE
```
=> Modified the office hours & communication section

README.md
Fixes #
Part of #409 
**TODOs**:
```release-note
NONE
```
=> Added docs section

README.md
Adds a github issues section to the Readme file for guiding contributors of how to open an issue.
Fixes #
Part of #409 
**TODOs**:
```release-note
NONE
```
=> Added github issues section

README.md
Fixes #113 
Part of #409 
**TODOs**:
```release-note
NONE
```
=> Added support policy to gcp

docs/flannel.md
I am currently trying to add a few docs to CAPG that will enhance the project. I am still browsing through other CAP* projects in in order understand the enhancement. 
Any sort of help related to addition to the docs will be helpful.
Fixes #
**TODOs**:
```release-note
Addition of flannel.md to the docs
```
=> Added flannel.md to the docs

CONTRIBUTING.md
Fixes #
**TODOs**:
```release-note
NONE
```
=> Improvements to contributing.md

.github/workflows/cover.yaml, .github/workflows/lint-link.yml, .markdownlinkcheck.json
This PR adds test for better code coverage and also adds markdown-link-checker that will check if there's any non existent link in any PR
Fixes #
**TODOs**:
```release-note
Improves linting configurations of the project
```
=> Improvement of github workflow and added test coverage

README.md
Minor fix
Fixes #
**TODOs**:
```release-note
```
=> Update CAPI image path from master->main

README.md
Fixed 2 broken links - prerequisites and development guide
Fixes #424 
**TODOs**:
```release-note
NONE
```
=> Fixed broken links // prerequisites, development guide

docs/book/src/developers/development.md, docs/book/src/developers/releasing.md
=> Replace Windows with Windows+WSL2

Dockerfile, Makefile, go.mod, main.go
/kind bug
/kind cleanup
- update go to 1.16.10
- fix the version when output that, that was using a wrong lib and was missing information
before 
```
I1111 17:50:45.287474   28154 deleg.go:130] setup "msg"="starting manager"  "version"="v0.0.0-master+$Format:%H$"
```
after
```
I1111 16:52:58.636173   80799 deleg.go:130] setup "msg"="starting manager"  "extended_info"={"major":"1","minor":"0","gitVersion":"v1.0.0-dirty","gitCommit":"c26a68b23e9317323d5d37660fe9d29b3d2ff40c","gitTreeState":"dirty","buildDate":"2021-11-11T15:44:39Z","goVersion":"go1.17.2","compiler":"gc","platform":"darwin/amd64"} "version"="v1.0.0-dirty"
```
/assign @dims @sayantani11 @jayesh-srivastava 
**Which issue(s) this PR fixes** *(optional, in …
=> version: fix version in the manager logs

Dockerfile, Makefile, scripts/ci-conformance-old.sh, scripts/ci-conformance.sh, templates/test/cluster-template-prow-ci-version.yaml, test/e2e/capi_test.go, test/e2e/common.go, test/e2e/config/gcp-ci.yaml, test/e2e/conformance_test.go, test/e2e/data/cni/calico/calico.yaml, test/e2e/data/kubetest/conformance.yaml, test/e2e/helpers.go, test/e2e/suite_test.go
/kind feature
/kind cleanup
Fixes #
**TODOs**:
```release-note
Refactor conformance tests to use the capi test suite framework
```
=> Refactor conformance tests to use the capi test suite framework

Dockerfile, Makefile, scripts/ci-conformance-old.sh, scripts/ci-conformance.sh, templates/test/cluster-template-prow-ci-version.yaml, test/e2e/capi_test.go, test/e2e/common.go, test/e2e/config/gcp-ci.yaml, test/e2e/conformance_test.go, test/e2e/data/cni/calico/calico.yaml, test/e2e/data/kubetest/conformance.yaml, test/e2e/helpers.go, test/e2e/suite_test.go
Signed-off-by: Carlos Panato <ctadeu@gmail.com>
/kind feature
cherry-pick: refactor conformance tests to run with the capi test suite
cherry pick of https://github.com/kubernetes-sigs/cluster-api-provider-gcp/pull/469
Fixes #
**TODOs**:
```release-note
cherry-pick: refactor conformance tests to run with the capi test suite
```
=> cherry-pick: refactor conformance tests to run with the capi test suite

Makefile, hack/ensure-go.sh, hack/ensure-kind.sh, hack/kustomize-sub.sh, hack/verify-shellcheck.sh, hack/version.sh, scripts/ci-build.sh, scripts/ci-conformance.sh, scripts/ci-e2e.sh, scripts/ci-make.sh, scripts/ci-test.sh, scripts/kind-with-registry.sh, scripts/setup-dev-enviroment.sh, tilt_modules/cert_manager/test/test.sh
This PR adds a bash script for shellcheck verification, and makes the changes required for the feature.
Fixes #482 
**TODOs**:
```release-note
Shellcheck verfication script added
```
=> Bash script added for shellcheck verification

Makefile, hack/install-cert-manager.sh, scripts/ci-conformance.sh, scripts/ci-e2e.sh, scripts/kind-with-registry.sh
Fixes #484 
**TODOs**:
```release-note
Align kubectl install and CI scripts to use local bin folder
```
=> Align kubectl install and CI scripts to use local bin folder

README.md
It fixes the issue with the broken link in README.md 
Fixes  #505
**TODOs**:
```NONE
```
=> update CAPI discussion link

README.md
The table needs to be updated for a better understanding of the compatibility of the release and that of K8s.
Fixes #485 
**TODOs**:
```release-note
Update the support policy according to a new release in README.md
```
=> Reflect changes on support policy section

Makefile, test/e2e/capi_test.go
/kind feature
- e2e/upgrade: add HA upgrade tests
need test-infra https://github.com/kubernetes/test-infra/pull/25238
/hold for test-infra pr and run the non required tests
/assign @dims @sayantani11 @jayesh-srivastava 
Fixes #
**TODOs**:
```release-note
e2e/upgrade: add HA upgrade tests
```
=> e2e/upgrade: add HA upgrade tests

test/e2e/capi_test.go, test/e2e/config/gcp-ci.yaml, test/e2e/data/infrastructure-gcp/cluster-template-kcp-remediation.yaml, test/e2e/data/infrastructure-gcp/cluster-template-md-remediation.yaml
/kind feature
- tests/e2e: add remediation tests
/hold for the tests
/assign @dims @sayantani11 @jayesh-srivastava 
Fixes #
**TODOs**:
```release-note
tests/e2e: add remediation tests
```
=> tests/e2e: add remediation tests

Dockerfile, hack/ensure-go.sh
/kind cleanup
- update go to 1.17.7
and also to test conformance-ci-artifacts due to some Testgrid failures https://testgrid.k8s.io/sig-cluster-lifecycle-cluster-api-provider-gcp#capg-conformance-main-ci-artifacts
Fixes #
**TODOs**:
```release-note
NONE
```
=> update go to 1.17.7

.github/workflows/link-check.yml
/kind feature
enables quiet mode for broken link check in docs.
Fixes #543 
No.
**TODOs**:
```release-note
quiet mode added for broken doc links
```
=> enable quiet mode for docs link checker

tilt-provider.json
Add CAPG label to Tilt so that the UX is consistent with CAPI and other providers. See the CAPG label on controller and binary.
BEFORE
AFTER
Fixes #
**TODOs**:
```release-note
NONE
```
=> Add CAPG label to tilt-provider.json

Makefile, scripts/ci-apidiff.sh
checks API changes on PRs
Fixes #
A part of #510 
**TODOs**:
```release-note
add ci-apidiff job along with apidiff target
```
=> add ci-apidiff job along with apidiff target

OWNERS, OWNERS_ALIASES
/kind cleanup
- owners: update capi owners members
- owners: cleanup and move members to emeritus
Please confirm if y'all are fine with this and we will apply a lazy consensus of two weeks, which ends on March 4th, 2022
/assign @dims @detiber @gab-satchi @justinsb @krousey @roberthbailey @rsmitty
cc @fabriziopandini @vincepri 
thanks for all the contributions to this project!
Fixes #
**TODOs**:
```release-note …
```
=> owners: cleanup and move members to emeritus

Makefile
Fixes#
A part of #510 
**TODOs**:
```release-note
None
```
=> Verify lint-fix added to Makefile

scripts/go_install.sh
/kind cleanup
Following up on #507, now that we're using go install we no longer need a temp dir.
Fixes #
**TODOs**:
```
NONE
```
=> Cleanup go install script

docs/book/src/developers/development.md
/kind cleanup
Existing method of getting source is failing, replaced it with `git clone` method.
Fixes #550 
**TODOs**:
```
NONE
```
=> Use `git clone` to get source

Makefile, Tiltfile, hack/verify-starlark.sh
The PR adds a target that verifies tiltfile
Fixes #
A part of #510 
**TODOs**:
```release-note
verify-tiltfile target  added
```
=> add verify-tiltfile target

.github/workflows/link-check.yml, .markdownlinkcheck.json
/kind bug
Fixes https://github.com/kubernetes-sigs/cluster-api-provider-gcp/issues/622
=> Fix GitHub Actions for Links 

docs/book/src/developers/development.md
The version of KIND in the CAPG doc is outdated (v0.11.1) in contrast to latest version (v0.14.0) which works completely fine for the local development purpose.  
**TODOs**:
=> update KIND version to latest

Makefile, Tiltfile, go.mod, go.sum, scripts/ci-conformance.sh, scripts/ci-e2e.sh, test/e2e/config/gcp-ci.yaml
/kind feature
- Update capi to 1.1.5 
- k8s capg images
Fixes #
**TODOs**:
```release-note
- Update capi to 1.1.5 
- k8s capg images
```
=> Update capi to 1.1.5 and k8s capg images

docs/book/src/developers/development.md
Current documentation lacked GoLand configuration under the debug section. 
**TODOs**:
```release-note
NONE
```
cc @cpanato
=> add GoLand configuration for debug section

Tiltfile, scripts/kind-with-registry.sh
/kind bug
Found some issues while setting up repo locally with Tilt. This PR fixes minor bugs in `scripts/kind-with-registry.sh` and `Tiltfile` files. More details is added to each commit description.
Nope.
Keeping separate commits as of now. If required I will squash them to one commit before merge.
**TODOs**:
~- [ ] includes documentation~
~- [ ] adds unit tests~
```release-note
NONE
```
=> Fix development setup issue

Makefile
Signed-off-by: Prajyot-Parab <prajyot.parab2@ibm.com>
/kind cleanup
- Bump apidiff version to v0.4.0
- Fix apidiff target to report only actual api changes
Fixes #592 
**TODOs**:
```release-note
Fix apidiff target
```
=> Fix apidiff target

cloudbuild.yaml
Signed-off-by: Prajyot-Parab <prajyot.parab2@ibm.com>
/kind cleanup
- Update cloudbuild to go 1.18
Fixes #
**TODOs**:
```release-note
Update cloudbuild to go 1.18
```
=> Update cloudbuild to go 1.18

docs/book/src/topics/prerequisites.md
`IMAGE_ID` export is missing from the prerequisites.md file.
Fixes #636
**TODOs**:
```release-note
NONE
```
=> docs: add IMAGE_ID export to prerequisites

Makefile, Tiltfile, go.mod, go.sum, test/e2e/config/gcp-ci.yaml
/kind feature
- update capi to v1.2.1
Fixes #
**TODOs**:
```release-note
update capi to v1.2.1
```
=> update capi to v1.2.1

api/v1beta1/types.go
/kind bug
We want this field to be optional.
Fixes #
**TODOs**:
```release-note
Marke EnableFlowLogs really optional
```
=> Marke EnableFlowLogs as optional

Makefile, Tiltfile, go.mod, go.sum, test/e2e/config/gcp-ci.yaml
Signed-off-by: cpanato <ctadeu@gmail.com>
/kind feature
- bump CAPI to v1.2.4
Fixes #
**TODOs**:
```release-note
bump CAPI to v1.2.4
```
=> bump CAPI to v1.2.4

Makefile
/kind other
Fixes #
**TODOs**:
```release-note
Bump k8s version for envtest
```
=> Bump k8s version for envtest

OWNERS, OWNERS_ALIASES
/kind other
Updates the maintainer list to remove myself from it (haven't contributed here in a while), and updates the reviewer list to only include this repo's maintainers.
Fixes #
**TODOs**:
```release-note
NONE
```
=> Remove myself from maintainers, update reviewer group

OWNERS_ALIASES
- add richardcase to capg maintainers
@richardcase are doing a great job reviewing PRs and providing great feedback and also help to mentoring in the LFX project last summer.
/assign @dims 
Fixes #
**TODOs**:
```release-note
NONE
```
=> add richardcase to capg maintainers

.codespellignore, .github/workflows/codespell.yml, CONTRIBUTING.md, cloud/interfaces.go, test/e2e/data/cni/calico/calico.yaml
/kind cleanup
Adds a Github Action for codespell and fixes existing issues in repository.
Fixes #681
If you'd like to test locally you can use something like [act](https://github.com/nektos/act) to locally run GH Actions (looks GH already picked up the check though 😄 ).
```
brew install act
act pull_request -j codespell
```
**TODOs**:
-->
```release-note
NONE
```
=> Add codespell and fix spelling issues

README.md
Fixes #579
Please verify the meeting details.
**TODOs**:
```release-note
Added CAPG monthly office hours details.
```
=> Added CAPG monthly office-hours details

docs/proposals/20221123-managed-kubernetes-in-capg.md
Add proposal for managed Kubernetes in CAPG (https://github.com/kubernetes-sigs/cluster-api-provider-gcp/issues/512)
Fixes #
**TODOs**:
```release-note
- Add proposal for managed Kubernetes in CAPG
```
=> Add proposal for managed Kubernetes in CAPG

Tiltfile, docs/book/src/developers/development.md, hack/boilerplate/boilerplate.py.txt, hack/boilerplate/boilerplate_test.py, hack/boilerplate/test/fail.py, hack/boilerplate/test/pass.py, hack/checkin_account.py, hack/checkout_account.py, hack/heartbeat_account.py, hack/install-cert-manager.sh, scripts/ci-conformance.sh, scripts/ci-e2e.sh
/kind feature
- update cert-manager to 1.11.0 release and use python3
this will fix https://testgrid.k8s.io/sig-cluster-lifecycle-cluster-api-provider-gcp#capg-conformance-main
Fixes #
**TODOs**:
```release-note
update cert-manager to 1.11.0 release
```
=> update cert-manager to 1.11.0 release and use python3

docs/book/src/developers/development.md, hack/boilerplate/boilerplate.py.txt, hack/boilerplate/boilerplate_test.py, hack/boilerplate/test/fail.py, hack/boilerplate/test/pass.py, hack/checkin_account.py, hack/checkout_account.py, hack/heartbeat_account.py, scripts/ci-conformance.sh, scripts/ci-e2e.sh
/kind cleanup
Fixes #
**TODOs**:
```release-note
use python3, python2 is deprecated
```
=> [release-1.1] use python3, python2 is deprecated

docs/book/src/developers/development.md, hack/boilerplate/boilerplate.py.txt, hack/boilerplate/boilerplate_test.py, hack/boilerplate/test/fail.py, hack/boilerplate/test/pass.py, hack/checkin_account.py, hack/checkout_account.py, hack/heartbeat_account.py, scripts/ci-conformance.sh, scripts/ci-e2e.sh
/kind cleanup
Fixes #
**TODOs**:
```release-note
use python3, python2 is deprecated
```
=> [release-1.2] use python3, python2 is deprecated

cloud/scope/clients.go, cloud/scope/cluster.go, cloud/scope/credentials.go, cloud/scope/managedcluster.go, cloud/scope/managedcontrolplane.go, cloud/scope/managedmachinepool.go, config/manager/manager.yaml, exp/api/v1beta1/gcpmanagedcontrolplane_webhook.go, exp/controllers/gcpmanagedcluster_controller.go, exp/controllers/gcpmanagedcontrolplane_controller.go, exp/controllers/gcpmanagedmachinepool_controller.go, feature/feature.go, main.go, templates/cluster-template-gke.yaml
/kind feature
This change adds the GKE feature flag to CAPG and adds the controllers to main.
Relates #512 
**TODOs**:
```release-note
Enables GKE support via new feature flag.
```
=> Add feature flag and enable controllers (GKE part 5)

Dockerfile, Makefile, test/e2e/data/infrastructure-gcp/cluster-template-prow-ci-version.yaml
/kind cleanup
**What this PR does / why we need it**:''
- Rename k8s.gcr.io to registry.k8s.io and go updates
/assign @richardcase 
Fixes #
**TODOs**:
```release-note
Rename k8s.gcr.io to registry.k8s.io and go updates
```
=> Rename k8s.gcr.io to registry.k8s.io and go updates

cloud/services/container/clusters/kubeconfig.go
/kind bug
**What this PR does / why we need it**: Minor fix, return correct error variable.
Fixes #
**TODOs**:
```
NONE
```
=> Return correct error variable

Dockerfile, Makefile, Tiltfile, go.mod, go.sum, test/e2e/config/gcp-ci.yaml
/kind feature
- update go to 1.19.7
- update CAPI to v1.3.5
/assign @richardcase 
/hold for all tests
Fixes #
**TODOs**:
```release-note
- update go to 1.19.7
- update CAPI to v1.3.5
```
=> Update GO to v1.19.7 and CAPI to v1.3.5

metadata.yaml, test/e2e/config/gcp-ci.yaml
/kind cleanup
- update metadata file to add the 1.5 releases
this was missing for the 1.5 series
/assign @richardcase @dims 
Fixes #
**TODOs**:
```release-note
update metadata file to add the 1.5 releases
```
=> update metadata file to add the 1.5 releases

main.go
/kind bug
Fixes #
**TODOs**:
```release-note
NONE
```
=> main: logged correct error in branch

README.md
The link to the docs in the README now points to the book. This PR also moves the documentation link up in the document so that it is more visible.
Fixes #
**TODOs**:
-->
```release-note
NONE
```
=> 📖  docs: link to book from readme

README.md
TODO:
```release-note
NONE
```
=> README: update CAPG meeting time

.github/dependabot.yml, .github/workflows/codespell.yml, .github/workflows/cover.yaml, .github/workflows/link-check.yml, .github/workflows/lint.yml, .github/workflows/pr-gh-workflow-approve.yaml, Dockerfile, Makefile, hack/tools/go.mod, netlify.toml
/kind cleanup
- ci cleanup and updates
- go bump to 1.21.9
/assign @richardcase @damdo 
Fixes #
**TODOs**:
```release-note
- ci cleanup and updates
- go bump to 1.21.9
```
=> CI and Go updates

.github/workflows/lint.yml
/kind bug
- fix lint job
/assign @damdo @richardcase 
Fixes #
**TODOs**:
```release-note
NONE
```
=> fix lint job

docs/book/src/SUMMARY.md, docs/book/src/developers/nightlies.md
📖 Add documentation for nightly builds
```release-note
NONE
```
=> Add documentation for nightly builds

docs/book/src/topics/prerequisites.md
Simple typofixes. "yo" -> "to" & drop duplicate "use"
**TODOs**:
```release-note
NONE
```
=> Typofix in prerequisites.md

cloud/scope/managedcontrolplane.go
This PR allow the creation of zonal GKE cluster. Before only regional GKE cluster could be created.
**TODOs**:
- [ x] squashed commits
- [x ] includes documentation
- [ x] adds unit tests
```release-note
feat: gke zonal cluster support
```
=> feat: gke zonal cluster support

.github/workflows/codespell.yml, .github/workflows/link-check.yml, .github/workflows/lint.yml
/kind cleanup
Fixes: https://github.com/kubernetes-sigs/cluster-api-provider-gcp/issues/1348
/assign @damdo @richardcase 
Fixes #
**TODOs**:
```release-note
NONE
```
=> update gh permissions

OWNERS_ALIASES
/kind feature
This PR proposes that @salasberryfin be moved to a reviewer of CAPG. The reasons for this proposal:
- Carlos has been driving the CAPG office hours consistently during 2024
- Carlos has been doing reviews on PR
- Carlos has been contributing his own PRs
This PR also updates the aliases for:
- SCL leads
- CAPI maintainers
Fixes #
**TODOs**:
```release-note
@salasberryfin  moves to become a reviewer …
```
=> [PROPOSAL] Add salasberryfin as reviewer

.github/workflows/lint.yml, Dockerfile
/kind cleanup
- Cleanup golangci-lint and bump go in dockerfile
/assign @salasberryfin @damdo 
Fixes #
**TODOs**:
```release-note
Cleanup golangci-lint and bump go in dockerfile
```
=> Cleanup golangci-lint and bump go in dockerfile

go.mod
=> go.mod drop unneded replaces

OWNERS, OWNERS_ALIASES
/kind other
Moving @richardcase from maintainer to emeritus status.
Fixes #
**TODOs**:
```release-note
NONE
```
=> chore: move richardcase to emeritus

README.md
I think this is the correct time, based on the agenda doc.
```release-note
NONE
```
=> chore: update README with correct office hours time

cloud/scope/machine.go
This will enable re-use in the upcoming MachinePool support.
```release-note
NONE
```
=> chore: refactor service account into a standalone function
