- boilerplate.go.txt
**What this PR does / why we need it**: Keeping the `/* ... */` syntax so that running `make gendeepcopy` and friends doesn't needlessly churn the generated files. This format is what is used by https://github.com/kubernetes-sigs/cluster-api even though the cluster provider skeleton diverged and used `//` syntax. 
Fixes #
```release-note
```
> Change the comment syntax in the boilerplate file.

- Gopkg.lock
- vendor/sigs.k8s.io/cluster-api/clusterctl/clusterdeployer/clusterdeployer.go
- vendor/sigs.k8s.io/cluster-api/clusterctl/cmd/create_cluster.go
- vendor/sigs.k8s.io/cluster-api/clusterctl/cmd/delete_cluster.go
**What this PR does / why we need it**: as per the PR title.
Fixes #
**Special notes for your reviewer**: I was thinking that pulling in the latest cluster-api dependency would remove a bunch of `cloud/google` code since it was removed upstream, but after looking at the diff I realized that code had already been pruned by deps. 
```release-note
NONE
```
/assign @justinsb
> Update the cluster-api dependency to get support for cluster deletion

- cmd/gce-controller/main.go
This allows us to specify glog flags like `--v=8`
```release-note
NONE
```
> Add goflag parsing to pflags

- cloud/google/machineactuator.go
Annoying that `go vet` didn't spot this one!
```release-note
NONE
```
> Fix glog.Info -> glog.Infof

- vendor/sigs.k8s.io/cluster-api/pkg/controller/machine/controller.go
We were always logging an error message, even if there was no error.
```release-note
NONE
```
> Don't always log an error message

- cloud/google/machineactuator.go
Note that one of these is probably a breaking change, because it is on
a label.  But this is the time to take the breakage.
```release-note
Fix typo in bootstrap label
```
> Fix typo: boostrap -> bootstrap

- README.md
Current version of the minikube (0.28.2) won't work with clusterctl. There is an opened issue upstream (https://github.com/kubernetes-sigs/cluster-api/issues/475).
Fixes #38 
```
NO
```
```release-note
NONE
```
> Be explicit that minikube <= 0.28.0 is required for now.

- README.md
- cmd/clusterctl/examples/google/addons.yaml.template
- config/rbac/rbac_role.yaml
Fixes a few issues with the getting started process
1. `clusterctl` runs locally and needs authorization to call to GCP.  README.md adds instructions for using the machine-controller serviceaccount
2. machine-controller creates an event in the default namespace when the machine is created.  The rbac template is changed to add full access to the event kind.
3.  `addons.yaml` is missing a version specification, and kubectl fails to apply (with an very unclear error).  `/v1` is added to the template.
> Update getting started instructions

- Gopkg.toml
- pkg/apis/gceproviderconfig/v1alpha1/gceclusterproviderconfig_types_test.go
- pkg/apis/gceproviderconfig/v1alpha1/gcemachineproviderconfig_types_test.go
Fixes #44
```release-note
NONE
```
> Remove ginkgo / gomega

- Dockerfile
- config/manager/manager.yaml
Equivalent of https://github.com/kubernetes-sigs/cluster-api/pull/609
```release-note
NONE
```
> Dockerfile: move manager from /root/ to /

- .gitignore
- README.md
State explicitly K8s version to be used in bootstrap cluster, to make the clusterctl command working with various versions of minikube. Kubernetes before v1.12 doesn't support sub-resources in CRDs.
Also ignore kubeconfig file generated by clusterctl.
Fixes #59
> State explicitly K8s version to be used in bootstrap cluster.

- config/rbac/rbac_role.yaml
Allows Machine's controller to update machines status. Otherwise I was getting an error `Error updating machine to link to node: machines.cluster.k8s.io "gce-master-hbmms" is forbidden: User "system:serviceaccount:gcp-provider-system:default" cannot update resource "machines/status" in API group "cluster.k8s.io" in the namespace "default"`
> Allow gcp-provider-manager-role to update Machine status

- cmd/clusterctl/examples/google/machine_setup_configs.yaml
- cmd/clusterctl/examples/google/provider-components.yaml.template
/etc/default/kubelet is not a shell script, it is read by systemd.
systemd does not support the += syntax for extending a variable.
```release-note
NONE
```
> Remove string concatenation in /etc/default

- config/default/kustomization.yaml
**What this PR does / why we need it**: Currently the instructions to run kustomize produce an error because the files it tries to load no longer exist (they were renamed in https://github.com/kubernetes-sigs/cluster-api-provider-gcp/pull/58). 
Fixes #
```release-note
NONE
```
/assign @justinsb
> Fix the name of kustomized files.

- cmd/clusterctl/examples/google/machine_setup_configs.yaml
- pkg/cloud/google/machineactuator.go
- pkg/cloud/google/metadata.go
There's no reason to generate it client-side, and this sets us up
nicely for more server-side generation.
```release-note
NONE
```
> Move cloud-config generation server-side

- cmd/clusterctl/examples/google/generate-yaml.sh
This PR fixes a bug with the generate-yaml.sh script that was causing the `CLUSTER_NAME` variable to not get updated in the generated machine.yaml file and thus deployment of a cluster to fail using the README instructions. This simply adds the same sed command that happens for other templates.
Here's an example of the error I was seeing:
```
F0228 17:12:20.060510   31053 create_cluster.go:60] unable to create control plane machine: error creating a machine object in namespace default: Machine.cluster.k8s.io "gce-master-8g5z6" is invalid: metadata.labels: Invalid value: "$CLUSTER_NAME": a valid label must be an empty string or consist of alphanumeric characters, '-', '_' or '.', and must start and end with an alphanumeric character (e.g. 'MyValue', …
```
> sed cluster_name in machines.yaml

- README.md
Specifies  kustomize v1.0.11 for clusterapi bootstrap yaml file generation because kustomize v2.x.x introduced incompatible changes that prevent file generation.
> Update README.md - Specify  kustomize v1.0.11

- README.md
Change cluster create syntax to use bootstrap instead of minikube option.
The kubernetes version required by ClusterAPI was previously passed using the --minikube option to the cluster create command. But, the --minikube option was removed some time ago from the cluster create command, in favor of using --bootstrap options to pass the kubernetes version.
Using the old syntax now fails with no explanation to the user as to how to solve the issue.
This PR updates the README so that users will conform to the correct command syntax.
> Update README.md - Change cluster create command to use bootstrap option instead of minikube.

- README.md
The command in the instructions is incorrect: `clusterctl` takes `--bootstrap-type`, not `----bootstrap-type`.
```release-note
NONE
```
> Remove ---- from clusterctl command in README

- pkg/cloud/google/machineactuator.go
In some cases `kubelet` and `controlplane` versions are copied from `Kubernetes` version. `Kubernetes` version contains an extra `v` from `kubelet & controlplane` version. That's why I striped `v` from `kubelet` and `controlplane` version.
> Strip `v` from `kubelet` and `controlplane` version

- cmd/clusterctl/examples/google/machine_setup_configs.yaml
- pkg/cloud/google/machineactuator_test.go
- pkg/cloud/google/machinesetup/config_types.go
- pkg/cloud/google/machinesetup/config_types_test.go
- pkg/cloud/google/metadata.go
Interested to see what folks think about this approach. This PR would add the ability to supply additional metadata to instances that get created by the provider. As it currently stands, there's only the "startup-script" metadata field that can be edited. I'd like to be able to squirrel other data away in metadata during instance creation time. This PR allows metadata to be specified as a list with name/value fields, like:
```bash
metadata:
- name: "startup-script"
value: |
#!/bin/bash
echo "this is metadata"
- name: "additional-data"
value: |
this: "just a test"
```
It allows us to keep the "startup-script" in it's current form, while also allowing for additions.
Fixes #122
> feat: support additional metadata for instances

- cloud/services/compute/instances.go
This PR updates how we parse the kubernetes version in the
instances.go and allows it to pass the semver check during machine creation.
Signed-off-by: Spencer Smith <robertspencersmith@gmail.com>
Fixes #156
> 🐛 fix: fix reading of semver for kube version 

- Makefile
Do the same as what we do in examples/generate.sh, pick up CLUSTER_NAME
environment variable.
Change-Id: I1b9d46a648f31d07cf7af254df9d4112b393c2d5
Fixes #
> Avoid hard coding the cluster name in Makefile

- examples/controlplane/controlplane.yaml
Until we track down the slow start up issue, we should bump to 20 minutes.
Change-Id: I764eb281fc61bf26aa591f593e9a1a9df1072f1c
Fixes #
> Reflect current state of slow startup

- go.mod
Want to pull in https://github.com/kubernetes-sigs/cluster-api/pull/1426
Fixes #
> Update to newer cluster ctl with better retry handling

- cloud/services/compute/instancegroup.go
- cloud/services/compute/loadbalancers.go
- controllers/gcpcluster_controller.go
- controllers/gcpmachine_controller.go
This PR fixes a bug where the GCPCluster would watch only GCPMachines that it owned, which the OwnerReference is never set for. Instead, we watch all GCPMachines in this case and reconcile the Cluster object as well.
It also adds support for deleting instance groups and it refactors the code in multiple methods under the cloud package.
Fixes #165 
Fixes #163
> 🐛 Fix GCPCluster watcher on GCPMachines / delete instance groups

- hack/checkin_account.py
- hack/checkout_account.py
- hack/ci/README.md
- hack/ci/e2e-conformance.sh
- hack/ensure-kind.sh
- scripts/ci-e2e.sh
Change-Id: I4a32f8bf7f54a86fbd88617e634b2fd8ed6a76a9
```
GCP_PROJECT=my_gcp_project GOOGLE_APPLICATION_CREDENTIALS=$HOME/my-service-account.json hack/ci/e2e-conformance.sh
```
We need a CI job that uses CAPG to start a cluster and run some e2e tests. The scripts in this PR can help with that.
Fixes #
> Add CI script for running e2e conformance tests

- examples/generate.sh
- hack/checkout_account.py
- hack/ci/e2e-conformance.sh
- scripts/ci-e2e.sh
- Add a router and cloud nat to ensure that the VM(s) can access the
internet to pull debs and docker images
- use a python based `envsubst` command for generating example
configuration and avoid installing yet another binary
- correct resource type in boskos is `"gce-project"`
- Ability to dump logs (loop through all the instances and try getting
as much information to save in log files)
- Add timeouts for things that may get stuck
- install ansible if it is missing (or prompt user if not running as
root)
- create a new user id for running the packer based build for image when
running in the CI environment. packer/ansible fails otherwise.
- Add loops to wait for things to start up before running tests
- Add more logs to be sure we checkin/checkout projects from boskos
- Also install …
> Harden ci scripts and get e2e working

- hack/ci/e2e-conformance.sh
- scripts/ci-e2e.sh
We currently default to 1.15.4 in sigs.k8s.io/image-builder. Ideally we need to ensure sigs.k8s.io/image-builder is tested with 1.16.0 which it does not seem to yet. So brute forcing to see if it will work.
Why do we need this? we are using k/k latest master e2e conformance tests in the CI jobs and CRD(s) were promoted in 1.16, so a bunch of Conformance tests fail
Change-Id: Ib8fe24c28863216eeea485cce1a670e41de7c15a
Fixes #
> Build/Use k8s 1.16.0 image in packer

- controllers/gcpmachine_controller.go
InitializeParams is an input-only field, and thus this validation was
causing panics.  In practice we want to prevent machine changes at the
API level, I believe, rather than here.
Fixes #
> 🐛 Don't try to validate disk size updates

- Makefile
- config/default/manager_image_patch.yaml
- hack/ci/e2e-conformance.sh
So far we have been using the `gcr.io/k8s-staging-cluster-api-gcp/cluster-api-gcp-controller:latest` container image by default. We should build and push an image from the source code into the project specific repo (that we get from boskos) and use that to start the gcp controller in the kind cluster. We should do the same irrespective of whether this is a periodic job or a pre-submit job to ensure that we are testing the exact changes by building the image from the code.
Change-Id: I2d2cc8dd2c6e3ad8808fbf4bc9130e115f00c050
Fixes #
> Build/use gcp cluster-api-provider image explicitly

- Makefile
- examples/cluster/cluster.yaml
- hack/ci/e2e-conformance.sh
Change-Id: Ia1438ba496707680309ff645962b4295439dc977
Fixes #
> Create a new network for us to use, still allow default to work

- hack/ci/e2e-conformance.sh
Add a `SKIP_CLEANUP` to let the cluster stay alive for help with debugging.
Change-Id: I0c970288b2c0ebabf0cf87255475223550e33fad
Fixes #
> ✨ Skip cleanup for local development scenario

- hack/ci/e2e-conformance.sh
>  ✨ Log a bunch more diagnostic information

- hack/ci/e2e-conformance.sh
attempt to fix failures in CI:
https://k8s-testgrid.appspot.com/sig-cluster-lifecycle-cluster-api-provider-gcp#e2e-tests-master
https://storage.googleapis.com/kubernetes-jenkins/logs/ci-cluster-api-provider-gcp-make-conformance-master/1181351396365045760/build-log.txt
testing with the updated path works locally.
NONE
/kind failing-test
/priority important-soon
/assign @dims
> hack/ci/e2e-conformance.sh: update the kustomize install path

- examples/generate.sh
`0.1.3` from https://github.com/kubernetes-sigs/cluster-api/releases/ 
`0.2.5` from https://github.com/kubernetes-sigs/cluster-api-bootstrap-provider-kubeadm/releases
Fixes #
> ✨Update to latest "stable" releases

- api/v1alpha2/types.go
- cloud/scope/cluster.go
- cloud/services/compute/firewalls.go
- cloud/services/compute/instancegroup.go
- cloud/services/compute/loadbalancers.go
- config/crd/bases/infrastructure.cluster.x-k8s.io_gcpclusters.yaml
Interested to see how everyone feels about this.
This PR will add the ability to pass in ports you wish to use for the front/backends of the LB that gets created by the GCP provider. This was useful for me because I wanted to change the port k8s is listening on from 6443 to 443 all the way through. After some discussion on the cluster-api slack, I moved the frontend port to  respect what might be set in `Cluster.Spec.ClusterNetwork.APIServerPort`. This matches what is supported in the AWS provider.
Signed-off-by: Spencer Smith <robertspencersmith@gmail.com>
> ✨ Allow the ability to configure frontend and backend port for LB

- hack/ci/e2e-conformance.sh
Cherry pick of #227 on release-0.2.
#227: Install kustomize under hack/tools, run make modules before
For details on the cherry pick process, see the [cherry pick requests](https://git.k8s.io/community/contributors/devel/sig-release/cherry-picks.md) page.
> Automated cherry pick of #227: Install kustomize under hack/tools, run make modules before

- Dockerfile
- config/default/manager_image_patch.yaml
- go.mod
- go.sum
Cherry pick of #226 on release-0.2.
#226: Update Go 1.12.10 and modules
For details on the cherry pick process, see the [cherry pick requests](https://git.k8s.io/community/contributors/devel/sig-release/cherry-picks.md) page.
> Automated cherry pick of #226: Update Go 1.12.10 and modules

- examples/generate.sh
- hack/ci/e2e-conformance.sh
- Bump the version of Kubernetes in the generate example script from 1.16.1 to 1.16.2
- Bump the version of Kubernrtes in the conformance test script
- 1.16.1 has (CVE-2019-11253)
> 🏃Bump kubernetes version in generated examples to 1.16.2

- config/manager/manager.yaml
- config/rbac/auth_proxy_service.yaml
Signed-off-by: Warren Fernandes <wfernandes@pivotal.io>
This PR fixes the label value of `control-plane` from `capa-controller-manager` to `capg-controller-manager`
Fixes #237
> 🐛Fix control-plane label to capg-controller-manager

- examples/generate.sh
Signed-off-by: Warren Fernandes <wfernandes@pivotal.io>
This PR includes the `NETWORK_NAME` env var and a sane default when generating example manifests. This is needed for easier ramp up for beginners working with the gcp provider.
Fixes #238
> 🐛Add NETWORK_NAME when generating example manifests

- cloud/scope/machine.go
- controllers/gcpmachine_controller.go
This PR will add the ability to fish out the internal and external IPs
associated with a gcpmachine resource and populate those values in
`.status.addresses`.
Signed-off-by: Spencer Smith <robertspencersmith@gmail.com>
> :sparkles: Add addresses to machine status

- cloud/services/compute/service.go
- controllers/gcpmachine_controller.go
- replace the word `EC2` in error message and comments with `GCE` or `GCP`
Fixes #243
> 🐛 Change error message to say gcp/gce instead of ec2

- config/crd/kustomization.yaml
- config/crd/patches/cainjection_in_gcpclusters.yaml
- config/crd/patches/cainjection_in_gcpmachines.yaml
- config/crd/patches/cainjection_in_gcpmachinetemplates.yaml
- config/crd/patches/webhook_in_gcpclusters.yaml
- config/crd/patches/webhook_in_gcpmachines.yaml
- config/crd/patches/webhook_in_gcpmachinetemplates.yaml
Some names of file and resources said `aws` instead of saying `gcp`
> 🏃 Replace names with aws to say gcp

- api/v1alpha3/gcpcluster_types.go
- api/v1alpha3/gcpmachine_types.go
- config/crd/bases/infrastructure.cluster.x-k8s.io_gcpclusters.yaml
- config/crd/bases/infrastructure.cluster.x-k8s.io_gcpmachines.yaml
Show more details about `gcpcluster` as shown in the following example
```
NAME            CLUSTER         READY   NETWORK
cluster-test1   cluster-test1   true    default
```
and `gcpmachine` as shown in the following example
```
NAME                           CLUSTER         STATE     READY   INSTANCEID                             MACHINE
cluster-test1-controlplane-0   cluster-test1   RUNNING   true    gce://gcp/us-east4-a/cluster-test1-controlplane-0   cluster-test1-controlplane-0
cluster-test1-controlplane-1   cluster-test1   RUNNING   true    gce://gcp/us-east4-b/cluster-test1-controlplane-1   cluster-test1-controlplane-1
cluster-test1-controlplane-2   cluster-test1   RUNNING   true    gce://gcp/us-east4-c/cluster-test1-controlplane-2 …
```
> ✨ Add printer columns for gcpcluster and gcpmachine

- hack/ci/e2e-conformance.sh
Cherry pick of #248 on release-0.2.
#248: work with pod utils - fix go/src directory location
For details on the cherry pick process, see the [cherry pick requests](https://git.k8s.io/community/contributors/devel/sig-release/cherry-picks.md) page.
> Automated cherry pick of #248: work with pod utils - fix go/src directory location

- examples/generate.sh
this change brings the generation of machinedeployment inline with generation of the other assets (cluster, controlplane)
Fixes #
> generate: don't concat machinedeployment output

- api/v1alpha3/gcpmachine_types.go
- api/v1alpha3/zz_generated.deepcopy.go
- cloud/scope/machine.go
- config/crd/bases/infrastructure.cluster.x-k8s.io_gcpmachines.yaml
- controllers/gcpmachine_controller.go
- examples/generate.sh
Renames the `ErrorMessage` and `ErrorReason` fields to `FailureMessage` and `FailureReason` in 
`GCPMachineStatus`.
**Which issue(s) this PR fixes** :
Fixes #256
> ⚠️Rename ErrorMessage and ErrorReason to FailureMessage and FailureReason

- config/certmanager/certificate.yaml
- config/certmanager/kustomization.yaml
- config/certmanager/kustomizeconfig.yaml
- config/crd/patches/cainjection_in_gcpclusters.yaml
- config/crd/patches/cainjection_in_gcpmachines.yaml
- config/crd/patches/cainjection_in_gcpmachinetemplates.yaml
- config/default/webhookcainjection_patch.yaml
- Rename cert-manager API group from certmanager.k8s.io to cert-manager.io to be compatible with cert-manager
>  ⚠️ Rename cert-manager API group from certmanager.k8s.io to cert-manager.io

- Makefile
test-infra has been updated to use GCB to build release version images,
so we no longer need to do it here in the repo.
Requires https://github.com/kubernetes/test-infra/pull/15624
Fixes #
> 🏃 Let GCB build release images

- .golangci.yml
- main.go
> :running: Exclude pprof lint warning in golangci-lint config

- cloud/scope/machine.go
- cloud/services/compute/instances.go
- config/rbac/role.yaml
- controllers/gcpmachine_controller.go
> :sparkles: Support bootstrap data in secret

- hack/ci/e2e-conformance.sh
Change the URL we use for the latest Kubernetes CI artifacts because of
a race condition in the old URL that sporadically resulted in flakey
tests because the container images were sometimes missing when the tests
ran.
Fixes #
> :running: Switch Kubernetes CI URL

- hack/ci/e2e-conformance.sh
Change the URL we use for the latest Kubernetes CI artifacts because of
a race condition in the old URL that sporadically resulted in flakey
tests because the container images were sometimes missing when the tests
ran.
(cherry picked from commit ccdb40f32465c19df173bfad6b0382ae70c73e26)
Fixes #
> :running: [0.2] Switch Kubernetes CI URL

- examples/controlplane/kustomizeversions.yaml
- examples/machinedeployment/kustomizeversions.yaml
Fixes the problem introduced by kubernetes/kubernetes#87585 (no more .deb generated on CI)
Fixes kubernetes/kubernetes#87960
/assign @ncdc @detiber
> 🐛 fix-failing-test

- config/manager/manager.yaml
- main.go
Adding liveness and readiness probes similar we added here: https://github.com/kubernetes-sigs/cluster-api-provider-aws/pull/1487 and https://github.com/kubernetes-sigs/cluster-api-provider-azure/pull/374
Fixes #
```release-note
- liveness and readiness probes added
```
/cc @vincepri
> ✨health: Add liveness and readiness probes

- templates/kustomizeversions.yaml
Conformance tests against k8s master are currently broken, this fixes errors related to the kustomize templating.
> :running: [ci-conformance] Fix kustomize template to remove ami reference

- Makefile
- controllers/gcpcluster_controller.go
- hack/ci/e2e-conformance.sh
- hack/ensure-kustomize.sh
- templates/kustomizeversions.yaml
Updates the script used during conformance testing against upstream k8s to remove bash variables other than the ones we replace with the call to envsubst, since envsubst is replacing them with empty strings currently.
> :running: [ci-conformance] Fix kustomize template to better handle envsubst

- hack/ci/e2e-conformance.sh
Fixes conformance test jobs where CI artifacts are not being tested, such as: https://prow.k8s.io/view/gcs/kubernetes-jenkins/logs/ci-cluster-api-provider-gcp-make-conformance-v1alpha3/1253298101955858434
> :running: [ci-conformance] Fix tests when not using CI artifacts

- hack/ci/e2e-conformance.sh
- Fixes unbound variable CI_VERSION in hack/ci/e2e-conformance.sh when run without CI_VERSION or USE_CI_ARTIFACTS set, such as in the failed periodic job here: https://prow.k8s.io/view/gcs/kubernetes-jenkins/logs/ci-cluster-api-provider-gcp-make-conformance-v1alpha3/1253661850336235521
> :running: [ci-conformance] fix unbound variable

- templates/cluster-template.yaml
This avoids the 63 character limit on the kubernetes.io/hostname label.
https://github.com/kubernetes/kubernetes/issues/90686
> Register only with first component of local_hostname

- hack/ci/e2e-conformance.sh
Fixes the conformance script for a recent change in imagee-builder (https://github.com/kubernetes-sigs/image-builder/pull/218)
> :running: Fix conformance script for recent image-builder change

- cloud/services/compute/instances.go
This PR adds a common tag named by cluster-name to all the nodes: control-plane and worker nodes
On creating a service type=LoadBalancer, creation of firewall rules gets aborted in the EnsureLoadBalancer functionality. With the common tag present, rules get created and external IP gets assigned to the service
Fixes #304
> 🐛 Added common tag for control-plane and worker nodes to resolve LoadBalancer issue

- hack/ci/e2e-conformance.sh
(Follow-up to https://github.com/kubernetes/test-infra/pull/18290.)
[Now](https://prow.k8s.io/view/gcs/kubernetes-jenkins/logs/ci-kubernetes-build/1288265272272097280) that the `ci/latest` version marker again represents a cross build of `kubernetes/kubernetes@master`, we should stop using the `ci/k8s-master` generic version marker.
ref: https://github.com/kubernetes/test-infra/blob/master/docs/kubernetes-versions.md, https://github.com/kubernetes/sig-release/issues/850
Signed-off-by: Stephen Augustus <saugustus@vmware.com>
Fixes: https://github.com/kubernetes/kubernetes/issues/93309
cc: @detiber
> hack/ci: Use ci/latest version marker for retrieving cross builds

- controllers/gcpcluster_controller.go
- controllers/gcpmachine_controller.go
- main.go
- util/reconciler/defaults.go
- util/reconciler/defaults_test.go
Add an option to a user to set the reconciliation timeout.
this also we have in other providers.
None
/assign @rsmitty @detiber
> ✨ manager: add reconcile timeout option

- main.go
Similar we have for other providers adding the event broadcaster
None
/assign @rsmitty @detiber
> ✨ manager: add event broadcaster

- hack/ci/e2e-conformance.sh
Use kubernetes 1.19 instead of master
maybe fix: https://kubernetes.slack.com/archives/C8TSNPY4T/p1603896882143400
xref: https://github.com/kubernetes/test-infra/pull/19752
Fixes #
/assign @detiber @rsmitty
> 🏃 conformance: use kubernetes 1.19 branch

- docs/prerequisites.md
Fixes link to git repo for image-builder in prerequisites that seems to have changed -
```
$ git clone https://sigs.k8s.io/image-builder.git
Cloning into 'image-builder'...
fatal: repository 'https://sigs.k8s.io/image-builder.git/' not found
```
> Update link to image-builder git repo

- docs/prerequisites.md
- hack/ci/e2e-conformance.sh
- fix image-builder rule - changed here: https://github.com/kubernetes-sigs/image-builder/pull/419
- Use latest k8s version when using ci artifacts
Fixes https://github.com/kubernetes/kubernetes/issues/96814
> 🏃 fix image-builder rule and Use latest k8s version when using ci artifacts

- api/v1alpha3/gcpcluster_types.go
- api/v1alpha3/zz_generated.deepcopy.go
- config/crd/bases/infrastructure.cluster.x-k8s.io_gcpclusters.yaml
- controllers/gcpcluster_controller.go
Added a field FailureDomains in GCPClusterSpec which if provided, would override the default behaviour where the GCPClusterStatus.FailureDomains are defaulted to all the zones in the specified region. This change would set only the provided zones to true.
This PR would control the cluster components creation in the specified zones and thus unblock #303 to some extent.
> ✨ Support FailureDomains override(optional) in GCPClusterSpec

- api/v1alpha3/types.go
- api/v1alpha3/zz_generated.deepcopy.go
- cloud/services/compute/network.go
- config/crd/bases/infrastructure.cluster.x-k8s.io_gcpclusters.yaml
In case where the network name is provided in GCPCluster configuration(for customisation) and the the network does not exist, in that case network and subnets are auto created by CAPG. In such a case router and Cloud NAT should also be auto created for the entire functionality to work. 
This change creates router and CloudNAT only if network is created by CAPG.
Fixes the issue partially #267
> ✨ Auto create Cloud NAT if network is created by CAPG

- .github/PULL_REQUEST_TEMPLATE.md
Using the new template :)
update the PR template to add the `kind` + `release notes` section
the plugin will work when this PR is merged: https://github.com/kubernetes/test-infra/pull/20114
Fixes #
**TODOs**:
```release-note
NONE
```
/assign @detiber @rsmitty
> docs: update PR template to add kind and release notes section

- api/v1alpha3/gcpmachine_types.go
- cloud/services/compute/instances.go
- config/crd/bases/infrastructure.cluster.x-k8s.io_gcpmachines.yaml
- config/crd/bases/infrastructure.cluster.x-k8s.io_gcpmachinetemplates.yaml
The PR adds support for preemptible instances
Fixes #
> Add support for preemptible instances

- api/v1alpha3/gcpmachine_types.go
- config/crd/bases/infrastructure.cluster.x-k8s.io_gcpmachines.yaml
- config/crd/bases/infrastructure.cluster.x-k8s.io_gcpmachinetemplates.yaml
/kind api-change
Using x-kubernetes-list-type with v1 CRDs requires that one specify that
the key field is either required or has a default value. In the case of
AdditionalMetadata, the key field should be required.
Signed-off-by: hasheddan <georgedanielmangum@gmail.com>
Partial revert of #342 
See https://github.com/kubernetes/kubernetes/issues/91395 for more info.
/assign @detiber @justinsb @cpanato 
**TODOs**:
```release-note
NONE
```
> Make AdditionalMetadata Key field required

- hack/ci/e2e-conformance.sh
Capture more information about containerd when we run the conformance CI job (basically capture the /etc/contained/config.toml) 
/kind feature
> Grab config.toml for containerd

- hack/ensure-go.sh
build-image job needs `go` as the container image it runs in does not have it.
https://testgrid.k8s.io/sig-cluster-lifecycle-image-pushes#capg-build-image-nightly
/kind feature
Fixes #
**TODOs**:
```release-note
NONE
```
> Install go if needed

- hack/ensure-go.sh
- hack/ensure-kind.sh
- hack/ensure-kubectl.sh
- hack/ensure-kustomize.sh
the OSTYPE check fails in some containers (that report `linux-musl`), also forgot to ensure $GOPATH/bin is present in PATH.
/kind bug
Fixes #
**TODOs**:
```release-note
NONE
```
> Better check for OSTYPE & ensure GOPATH/bin is in PATH

- cloudbuild.yaml
/kind cleanup
The post job that builds the CAPG image is failing due job timeout
https://prow.k8s.io/?job=post-cluster-api-provider-gcp-push-images
one job for example: https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/post-cluster-api-provider-gcp-push-images/1402942988375560192
This PR increase to job timeout to 1 hour
/assign @dims 
Fixes #
**TODOs**:
```release-note
NONE
```
> cloudbuild: increase job timeout

- .golangci.yml
- api/v1alpha3/gcpmachine_types.go
- api/v1alpha3/groupversion_info.go
- api/v1alpha4/gcpcluster_webhook.go
- api/v1alpha4/gcpmachine_types.go
- api/v1alpha4/gcpmachine_webhook.go
- api/v1alpha4/groupversion_info.go
- cloud/gcperrors/errors.go
- cloud/scope/getters.go
- cloud/scope/machine.go
- cloud/services/compute/firewalls.go
- cloud/services/compute/instancegroup.go
- cloud/services/compute/instances.go
- cloud/services/compute/loadbalancers.go
- cloud/services/compute/network.go
- cloud/services/compute/regions.go
- cloud/services/compute/service.go
- cloud/wait/wait.go
- controllers/gcpmachine_controller.go
- controllers/gcpmachine_controller_unit_test.go
- hack/boilerplate/test/fail.go
- util/reconciler/defaults.go
- version/version.go
Signed-off-by: Carlos Panato <ctadeu@gmail.com>
/kind cleanup
golangci-lint: update golangci rules and fix the lints
Fixes: https://github.com/kubernetes-sigs/cluster-api-provider-gcp/issues/368
**TODOs**:
```release-note
NONE
```
> golangci-lint: update golangci rules and fix the lints

- .github/workflows/lint.yml
- scripts/ci-test.sh
/kind cleanup
follow up of https://github.com/kubernetes-sigs/cluster-api-provider-gcp/pull/384#issuecomment-864897185
this adds the golangci-lint to run in the github actions
Fixes #
**TODOs**:
```release-note
NONE
```
> ci: add golangci-lint to run using github-actions

- Makefile
- hack/ci/e2e-conformance.sh
- hack/ensure-kubectl.sh
Use dl.k8s.io instead of hardcoded GCS URIs
/kind cleanup
The only time a kubernetes GCS bucket name should be showing up in a
hardcoded URI is if `gsutil` is being used (e.g. gsutil cp gs://foo/bar .)
Otherwise, for tools like `curl` or `wget`, dl.k8s.io is much nicer for us
as a project, since we can transparently change where that redirects to
without having to change code everywhere
These changes will mean no changes will be necessary to accommodate a
`gs://kubernetes-release` -> `gs://k8s-release` migration equivalent of
the CI migration we're going through right now
These changes also address the `gs://kubernetes-release-dev` references
currently used by this repo (ref: …
> use dl.k8s.io instead of hardcoded GCS URIs

- hack/ci/e2e-conformance.sh
- scripts/ci-e2e.sh
- templates/cluster-template.yaml
/kind feature
we can use pre-built node images to accelerate a bit the CI tests, for conformance we now have two jobs that can run for PRs
- `pull-cluster-api-provider-gcp-conformance` - it uses the prebuilt node image and a fixed k8s version, currently is 1.19
- `pull-cluster-api-provider-gcp-conformance-ci-artifacts` - build the node image and use the latest CI available
I will work to convert the conformance to use the capi framework after we merge this
/assign @dims 
Fixes #
_Please confirm that if this PR changes any image …
> ci: use prebuilt node images for CAPG

- cloud/scope/clients.go
- cloud/scope/cluster.go
- cloud/services/compute/loadbalancers/reconcile.go
- cloud/services/compute/loadbalancers/service.go
- go.mod
- go.sum
/kind cleanup
Use GA TargetTcpProxies instead of Beta version after added in upstream https://github.com/GoogleCloudPlatform/k8s-cloud-provider/pull/61
**TODOs**:
```release-note
None
```
> Use GA TargetTcpProxies after updated upstream

- README.md
Fixed the table of GCP providers vs Kubernetes versions in the [Support policy](https://github.com/kubernetes-sigs/cluster-api-provider-gcp#support-policy) (2nd table).
**PS**: Brought the alignment of ticks to center for a better view
Fixes #435 
**TODOs**:
```release-note
NONE
```
> Correction made in the support policy section

- main.go
This change adds a ready and health check on the webhook server.
Signed-off-by: Jaybatra <jaybatra73@gmail.com>
Fixes #
**TODOs**:
```release-note
NONE
```
> Wait for webhook readiness and healthy

- controllers/suite_test.go
/kind cleanup
Replaces some occurrences of `Expect(err).ToNot(HaveOccurred())` with `Expect(err).NotTo(HaveOccurred())` (ToNot -> NotTo)
Fixes #
```NONE
```
> Replace some occurences of ToNot(HaveOccurred())

- Makefile
- hack/install-cert-manager.sh
This PR adds a cert manager installation script making the Makefile more resilient
Fixes #480 
**TODOs**:
```release-note
Addition of Cert Manager installation script
```
> Make cert manager install in makefile more resilient

- scripts/go_install.sh
/kind cleanup
The PR replaces `go get` with `go install`, as the use of `go get` to build and install packages is deprecated.
Fixes #492 
**Release note:**
```
NONE
```
> Replaced `go get` with `go install` to install binaries

- config/manager/manager.yaml
- config/rbac/kustomization.yaml
- config/rbac/leader_election_role_binding.yaml
- config/rbac/role_binding.yaml
- config/rbac/service_account.yaml
/kind feature
Uses a dedicated service account for each CAPG controller instead of the default.
Fixes #493 
**TODOs**:
```
Use custom service accounts instead of default for controllers.
```
> Use custom service accounts instead of default for controllers

- test/e2e/capi_test.go
- test/e2e/config/gcp-ci.yaml
- test/e2e/data/infrastructure-gcp/cluster-template-topology.yaml
- test/e2e/data/infrastructure-gcp/clusterclass-quick-start.yaml
/kind feature
As part of https://github.com/kubernetes-sigs/cluster-api-provider-gcp/issues/561, an effort to support managed topology (ClusterClass-based cluster) in CAPG, added e2e test to verify that a cluster can be successfully created with ClusterClass.
Enabled CLUSTER_TOPOLOGY feature flag, added a new flavor, topology, and quick-start ClusterClass for the test.
Fixes #560
**TODOs**:
```release-note
Add ClusterClass quickstart e2e test and ClusterClass template
```
> Add ClusterClass quickstart e2e test

- Makefile
- scripts/ci-e2e.sh
/kind other
For local e2e testing, GINKGO_NODES set to 3 makes it difficult to follow test output and debug.
This changes the default GINKGO_NODES to 1 but set GINKGO_NODES to 3 for CI
e2e tests to enable parallel testing and preserve the original behavior.
Fixes #
**TODOs**:
```release-note
NONE
```
> Change the default GINKGO_NODES to 1

- docs/book/src/developers/development.md
Add instruction to add GOOGLE_APPLICATION_CREDENTIALS env var before
testing so the test doesn't fail due to "google: could not find default
credentials"
Signed-off-by: Aniruddha Basak <codewithaniruddha@gmail.com>
Add info about adding GCP credentials before testing. So it will ease the process for the person using the project for the first time.
Fixes #
**TODOs**:
```release-note
Doc: Add …
```
> Doc: Add instruction to export gcp credential env var

- README.md
/kind bug
The PR fix the broken image link in [README.md](https://github.com/kubernetes-sigs/cluster-api-provider-gcp/blob/main/README.md)
Fixes #604 
**TODOs**:
```release-note
NONE
```
> Fix Cluster API image link in README.md

- cloud/scope/machine.go
- cloud/services/compute/instances/reconcile_test.go
- test/e2e/data/infrastructure-gcp/cluster-template-ci.yaml
- test/e2e/data/infrastructure-gcp/cluster-template-kcp-remediation.yaml
- test/e2e/data/infrastructure-gcp/cluster-template-md-remediation.yaml
- test/e2e/data/infrastructure-gcp/cluster-template-prow-ci-version.yaml
- test/e2e/data/infrastructure-gcp/cluster-template-topology.yaml
- test/e2e/data/infrastructure-gcp/cluster-template-upgrades.yaml
Signed-off-by: Aniruddha Basak <codewithaniruddha@gmail.com>
/kind feature
This PR is about picking a zone automatically when failureDomain is not specified in MachineDeployment
Fixes [#569](https://github.com/kubernetes-sigs/cluster-api-provider-gcp/issues/569#)
**TODOs**:
```release-note
Pick a zone for worker nodes automatically
```
> Pick a zone for worker nodes automatically when a failureDomain is not specified in MachineDeployment

- docs/book/src/developers/releasing.md
- docs/book/src/topics/prerequisites.md
> Fix Typo to `prerequisites.md`

- cloud/scope/cluster.go
- cloud/services/compute/firewalls/reconcile.go
- cloud/services/compute/instances/reconcile.go
- cloud/services/compute/networks/reconcile.go
/kind bug
We've experienced some issue where deleting of a CAPG cluster results in the delete reconciliation getting stuck. 
In one scenario the InstanceGroup is removed without all the instances being removed and upon the next reconcile loop the code error's out when trying to find the InstanceGroup. This PR allows that to silently fail as we want to continue with the clean up of other resources anyway.
Another issue we saw was the `.Status.Network.SelfLink` being cleared but subsequent delete reconcile loops attempting to use it to build the firewall rules object - resulting in a nil pointer panic. Rather than referencing the SelfLink, we instead build the partial URL from the known project and network name.
**Which …
> Improve resilience of cluster delete

- docs/book/src/developers/development.md
Add instruction to use the same k8s version as building the GCE image
Signed-off-by: Aniruddha Basak <codewithaniruddha@gmail.com>
The current information [here](https://github.com/kubernetes-sigs/cluster-api-provider-gcp/blob/main/docs/book/src/developers/development.md#tilt-for-dev-in-capg) about the `KUBERNETES_VERSION` env variable version is being 1.23.3 my control plane is not getting ready if my GCE OS image is not the same as the version mentioned. So adding a note about checking the version while building the OS image and exporting afterward will always help. 
**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) …
> Add info about the kubernetes version env variable

- api/v1beta1/types.go
- config/crd/bases/infrastructure.cluster.x-k8s.io_gcpclusters.yaml
- config/crd/bases/infrastructure.cluster.x-k8s.io_gcpclustertemplates.yaml
/kind bug
It seems like a copy paste error. The field name doesn't match with the field name when marshalling. I think this is a breaking change.
```release-note
Fix EnableFlowLogs field name
```
> fix: use right name for EnableFlowLogs field

- cloud/scope/cluster.go
/kind bug
The controller tries to create a legacy network instead of a VPC network when setting `autoCreateSubnetnetworks` to false, because the field is not sent to the google cloud API.
```release-note
Always send autoCreateSubnetnetworks to gcloud to force VPC network creation
```
> fix: always send autoCreateSubnetnetworks field to create VPC network

- Tiltfile
- docs/book/src/developers/development.md
/kind cleanup
Ran into some minor things when going through the Development getting started documentation:
* Minor typos in `development.md`, and a dead link / unclear instructions on creating a workload cluster
* Typo in an error message in the Tiltfile
* Bad string concatination in the Tiltfile that was resulting in invalid kubectl commands, such as `kubectlwait <...remainder of args...>` as opposed to `kubectl wait <...remainder of args...>`
**TODOs**:
```release-note
NONE
```
> Minor docs / Tiltfile cleanup

- cloud/scope/machine.go
/kind bug
We are using [externally managed cluster infrastructure](https://github.com/kubernetes-sigs/cluster-api/blob/main/docs/proposals/20210203-externally-managed-cluster-infrastructure.md) and nothing sets failure domain on cluster object, this makes controller panic when it's missing. I believe the controller should not panic here and fail in another place in this case.
Fixes #
**TODOs**:
```release-note …
```
> Fix panic when no failure domain found

- api/v1beta1/gcpclustertemplate_webhook_test.go
/kind failing-test
More like "not running" test rather than failing
Parallel test closures execute in a goroutine, possibly after the next
loop iteration has already began. As a result, the loop var they
capture changes before the test execute, leading to all of them
executing just the last test in the list.
This fixes that by making the closure capture a local variable rather
than the loop variable
None
```release-note
NONE
```
> Fix broken `TestGCPClusterTemplate_ValidateUpdate` test

- templates/cluster-template.yaml
Fixes https://github.com/kubernetes-sigs/cluster-api-provider-gcp/issues/683
**TODOs**:
```release-note
Removes hardcoding failureDomain in the default cluster-template.yaml
```
/kind bug
> Remove Hardcoded failureDomain in Template

- .gitignore
- Makefile
- scripts/ci-test-coverage.sh
/kind other
Running the `make` target for running tests with coverage fails
```
make test TEST_ARGS=" -coverprofile=out/coverage.out"
make[1]: Entering directory '/home/jose/dev/src/github.com/kubernetes-sigs/cluster-api-provider-gcp'
KUBEBUILDER_ASSETS="/home/jose/.local/share/kubebuilder-envtest/k8s/1.23.3-linux-amd64" go test ./... -coverprofile=out/coverage.out
open /home/jose/dev/src/github.com/kubernetes-sigs/cluster-api-provider-gcp/out/coverage.out: no such file or directory
make[1]: *** [Makefile:161: test] Error 1
make[1]: Leaving directory '/home/jose/dev/src/github.com/kubernetes-sigs/cluster-api-provider-gcp'
make: *** [Makefile:184: test-cover] Error 2
```
I checked [how capz is doing …
> Fix make target for test with coverage

- hack/install-cert-manager.sh
Feature, upgrade the Cert Manager version to `v1.9.1`
Installs the latest version `v.1.9.1`(at the moment) when executing the script: `hack/install-cert-manager.sh`
We are using the `v1.7.1`.
Cert Manager releases: [link](https://cert-manager.io/docs/installation/supported-releases/)
Cert Manager Release 1.9: [link](https://cert-manager.io/docs/release-notes/release-notes-1.9/)
_There is no issue crated_
Yes, this is the only …
> feat: Upgrade Cert-Manager version to the latest(v1.9.1)

- Makefile
- Tiltfile
- go.mod
- go.sum
- hack/install-cert-manager.sh
- test/e2e/config/gcp-ci.yaml
/kind feature
- update capi to v1.1.6
- update certmanager to v1.9.2
Fixes #
**TODOs**:
```release-note
- update capi to v1.1.6
- update certmanager to v1.9.2
```
> update capi to v1.1.6

- cloud/scope/cluster.go
/kind bug
When creating a new [proxy-only subnet](https://cloud.google.com/load-balancing/docs/proxy-only-subnets) using the `REGIONAL_MANAGED_PROXY` purpose, we need to pass the subnet Role.
**TODOs**:
```release-note
Set subnet role to ACTIVE
```
> Subnet role must be passed

- feature/feature.go
- feature/gates.go
- go.mod
- main.go
Adds the ability to use feature gates.
Fixes #643 
**TODOs**:
```release-note
Adding features via feature gate
```
/feature
> feat: Add support for feature gates

- cloud/scope/cluster.go
- cloud/services/compute/instances/reconcile_test.go
- cloud/services/compute/subnets/reconcile_test.go
/kind bug
Running unit tests with no real GCP credentials fails with the following error:
```
--- FAIL: TestService_createOrGetInstance (0.00s)
reconcile_test.go:142: failed to create gcp compute client: google: could not find default credentials. See https://developers.google.com/accounts/docs/application-default-credentials for more information.
```
This is because the compute service gets initialized here https://github.com/kubernetes-sigs/cluster-api-provider-gcp/blob/main/cloud/scope/cluster.go#L53 and it always tries to use real credentials.
Fixes #
**Special …
> Fix compute service initialization in tests

- cloud/scope/cluster.go
/kind bug
When `Cluster.ClusterNetwork` is not set in a deployed cluster, the provider will panic in a loop trying to reconcile the object.
`Cluster.ClusterNetwork` is a pointer and may be nil, ensure that the provider does not panic in this case.
Seems like a minor fix, and the code already falls back to a value if none is set, so I don't believe there are any changes needed for tests / docs.
**TODOs**: …
> Fix panic when ClusterNetwork is nil

- docs/book/src/topics/machine-locations.md
Adds section to docs about machine location.
Kudos to @itspngu -- This reattempts to merge https://github.com/kubernetes-sigs/cluster-api-provider-gcp/pull/455.
I unfortunately couldn't cherry-pick it as the original repo is deleted, but think this information is still highly relevant and important to people who are getting started with CAPG.
Related to #444
**TODOs**:
```release-note
NONE
```
> docs: Add section about Machine Location

- docs/book/src/topics/gke/cluster-upgrades.md
- docs/book/src/topics/gke/creating-a-cluster.md
- docs/book/src/topics/gke/disabling.md
- docs/book/src/topics/gke/enabling.md
- docs/book/src/topics/gke/index.md
This change adds relevant docs for the GKE feature in CAPG.
Relates #512
**TODOs**:
```release-note
Add documentation for the GKE feature
```
> Add docs (GKE part 8)

- exp/api/v1beta1/gcpmanagedcluster_webhook.go
- exp/api/v1beta1/gcpmanagedcontrolplane_webhook.go
- exp/api/v1beta1/gcpmanagedmachinepool_webhook.go
/kind feature
This change adds validation webhooks for `GCPManagedCluster`, `GCPManagedControlPlane`, and `GCPManagedMachinePool`.
Relates #512
**TODOs**:
```release-note
Add validation webhooks for **GCPManagedCluster**, **GCPManagedControlPlane**, and **GCPManagedMachinePool**
```
> Add validation webhooks (GKE part 7)

- Makefile
/kind other
cc: @richardcase @cpanato 
I updated the URL for the YAML manifest installing Calico on a workload cluster (consulted [CAPI - Quick Start](https://cluster-api.sigs.k8s.io/user/quick-start.html#deploy-a-cni-solution) doc)
**Which issue(s) this PR fixes**
- The Make command `make create-workload-cluster` failed on installing Calico:
```bash
/home/pnguyen4/Coding/cluster-api-provider-gcp/hack/tools/bin/kubectl-v1.25.5 --kubeconfig="/tmp/kubeconfig" apply -f https://docs.projectcalico.org/manifests/calico.yaml
error: unable to read URL "https://docs.projectcalico.org/manifests/calico.yaml", server reported 404 Not Found, status code=404
make: *** [Makefile:504: create-workload-cluster] Error 1
```
- The old URL …
> Update URL for Calico's manifest in Makefile

- .gitignore
/kind other
Some vendored folder are named kubeconfig and are being ignored by .gitignore
E.g.:
vendor/sigs.k8s.io/kind/pkg/cluster/internal/kubeconfig/internal/kubeconfig/encode.go
This causes issues when working with these files in git when vendoring. 
I have added `!**/kubeconfig/` to only ignore files named kubeconfig and not directories.
**TODOs**:
```release-note
NONE
```
> Do not ignore kubeconfig directory

- config/crd/bases/infrastructure.cluster.x-k8s.io_gcpmanagedcontrolplanes.yaml
- exp/api/v1beta1/gcpmanagedcontrolplane_types.go
/kind feature
Make GKE enableAutopilot field optional.
Error out otherwise:
```
error: error validating "capi-gke-quickstart.yaml": error validating data: ValidationError(GCPManagedControlPlane.spec): missing required field "enableAutopilot" in io.x-k8s.cluster.infrastructure.v1beta1.GCPManagedControlPlane.spec; if you choose to ignore these errors, turn validation off with --validate=false
```
None
**TODOs**: …
> Make GKE enableAutopilot optional

- Dockerfile
- Makefile
- Tiltfile
- go.mod
- go.sum
- test/e2e/config/gcp-ci.yaml
/kind feature
- Update CAPI to v1.3.8
/assign @richardcase 
Fixes #
**TODOs**:
```release-note
NONE
```
> Update CAPI to v1.3.8

- cloud/scope/cluster.go
/kind feature
In some cases when kubelet running on a node accidentally stops working, it can lead to errors since the node appears as healthy backend in the apiserver load balancer even though etcd probe is returning `etcd failed reason withheld`
```bash
[+]ping ok
[+]log ok
[-]etcd failed: reason withheld
[+]informer-sync ok
[+]poststarthook/start-kube-apiserver-admission-initializer ok
[+]poststarthook/generic-apiserver-start-informers ok
[+]poststarthook/priority-and-fairness-config-consumer ok
[+]poststarthook/priority-and-fairness-filter ok
[+]poststarthook/start-apiextensions-informers ok
[+]poststarthook/start-apiextensions-controllers ok
[+]poststarthook/crd-informer-synced ok …
```
> chore: improve apiserver loadbalancer healthcheck

- docs/book/src/developers/cluster-creation.md
- docs/book/src/topics/prerequisites.md
- scripts/ci-conformance.sh
- scripts/ci-e2e.sh
/kind cleanup
- build-gce-ubuntu-1804 is deprecated update to build-gce-ubuntu-2004
/hold for all non required tests
Fixes #
**TODOs**:
```release-note
build-gce-ubuntu-1804 is deprecated update to build-gce-ubuntu-2004
```
> build-gce-ubuntu-1804 is deprecated update to build-gce-ubuntu-2004

- .gitignore
/kind other
Some vendored files are named `coverage.go` and are being ignored by `.gitignore`'s https://github.com/kubernetes-sigs/cluster-api-provider-gcp/blob/797df124dd04047257411b733e91fef7c0c1581c/.gitignore#L17
E.g.:
```
vendor/golang.org/x/text/internal/language/coverage.go
vendor/golang.org/x/text/language/coverage.go
```
This causes issues when working with these files in git when vendoring.
**TODOs**:
```release-note
NONE
```
> Do not ignore coverage.go

- cloud/services/container/clusters/kubeconfig.go
/kind feature
This PR adds `gcloud-auth` authentication in the user kubeconfig secret.
Fixes #923 
**TODOs**:
```
Add `gcloud-auth` authentication
```
> Add gcloud auth in user kubeconfig secret

- Dockerfile
- scripts/ci-make.sh
- test/e2e/data/infrastructure-gcp/cluster-template-prow-ci-version.yaml
/kind feature
- Switch to Kubernetes Community-Owned Package Repositories
- Removed kubectl --short flag (deprecated)
- bump go to 1.20.11
Fixes #
**TODOs**:
```release-note
- Switch to Kubernetes Community-Owned Package Repositories
- Removed kubectl --short flag (deprecated)
- bump go to 1.20.11
```
> Switch to Kubernetes Community-Owned Package Repositories and update go 1.20.11

- cloud/services/container/nodepools/reconcile.go
/kind bug
When the nodeLocations field of the GCPManagedMachinePool object is empty, this error appears in the reconcile process:
"error"="node pool config update (either version/labels/taints/locations/image type/network tag or all) failed: rpc error: code = InvalidArgument desc = At least one of ['node_version', 'image_type', 'updated_node_pool', 'locations', 'workload_metadata_config', 'upgrade_settings', 'kubelet_config', 'linux_node_config', 'tags', 'taints', 'labels', 'node_network_config', 'gcfs_config', 'gvnic', 'confidential_nodes', 'logging_config', 'fast_socket', 'resource_labels', 'accelerators', 'windows_node_config', 'machine_type', 'disk_type', 'disk_size_gb', 'containerd_config', 'resource_manager_tags'] …
> Fix update node pool when nodeLocation is empty

- cloud/scope/managedmachinepool.go
/kind bug
"When the version is configured in the Machine Pool object, a 'v' is added, and the reconciliation process fails with the following error:"
E1201 12:53:35.740062     515 gcpmanagedmachinepool_controller.go:342]  "msg"="Reconcile error" "error"="node pool config update (either version/labels/taints/locations/image type/network tag or all) failed: rpc error: code = InvalidArgument desc = Version \"v1.27.3-gke.100\" is invalid. It should have the form 1.X, 1.X.Y, 1.X.Y-.*, 'latest', or ''.
**TODOs**:
```release-note
NONE
```
> Fix GKE reconciliation when the version is set in the machine pool

- cloud/services/container/clusters/reconcile.go
/kind bug
The GKE update process enters an infinite loop during the reconcile process because it compares desiredMasterVersion to InitialClusterVersion instead of CurrentMasterVersion.
**TODOs**:
```release-note
Use current cluster version when upgrading a GKE cluster instead of the initial version. 
```
> Fix GKE update version check

- cloud/scope/cluster.go
- cloud/scope/managedcluster.go
/kind bug
fixes #1058 
**TODOs**:
```release-note
Fix a bug to support `secondyCidrBlocks`.
```
> Pass required RangeName to compute.SubnetworkSecondaryRange

- cloud/scope/managedmachinepool.go
- cloud/services/container/nodepools/reconcile.go
- cloud/services/shared/machinepool.go
/kind bug
MachinePool replicas should be set based on the number of regions specified for that MachinePool.
**TODOs**:
```release-note
Fix GKE MachinePool number of replicas, now are based on the number of regions specified for that MachinePool.
```
> Fix GKE MachinePool replicas per region

- cloud/services/container/clusters/reconcile.go
/kind bug
In GKE the patch number is stripped in the MachinePool object but not in GCPManagedControlPlane.
**TODOs**:
```release-note
Strip the patch number in GKE master version.
```
> Strip the patch number in GKE master version

- cloud/services/container/nodepools/reconcile.go
- exp/api/v1beta1/types.go
/kind bug
When the version is defined in the MachinePool object, the following error occurs in the reconciliation process:
E1211 13:28:24.009959       1 gcpmanagedmachinepool_controller.go:342]  "msg"="Reconcile error" "error"="node pool config update (either version/labels/taints/locations/image type/network tag or all) failed: rpc error: code = InvalidArgument desc = Version \"v1.27.3-gke.100\" is invalid. It should have the form 1.X, 1.X.Y, 1.X.Y-.*, 'latest'
**TODOs**:
```release-note
Fix GKE reconciliation process when MachinePool version is set.
```
> Fix node pool update when MachinePool version is set

- cloud/services/container/nodepools/reconcile.go
- exp/api/v1beta1/types.go
- tilt-provider.json
/kind bug
The reconciliation process is broken in GKE. When enableAutoscaling is not defined, the reconciliation process fails because desiredAutoscaling is nil and when it is defined, it fails because the state is unexported.
**TODOs**:
```release-note
Fix GKE autoscaling conditions in reconciliation process.
```
> Fix GKE autoscaling conditions in reconciliation process

- Dockerfile
- metadata.yaml
- scripts/ci-e2e.sh
- test/e2e/capi_test.go
- test/e2e/config/gcp-ci.yaml
/kind bug
/kind cleanup
- update golang to 1.21.7 in dockerfile and other updates
/assign @richardcase 
I've commented out a test that will require a bit more testing
Fixes #
**TODOs**:
```release-note
update golang to 1.21.7 in dockerfile and other updates
```
> update golang to 1.21.7 in dockerfile and other updates

- config/manager/manager.yaml
/kind bug
It fixes an invalid containerPort in the manager Deployment's config.
The string was set as an envsubst string but the containerPort field is an int32, and this may break at kustomization/parsing time depending on how the tooling is configured (e.g. for the upstream cluster-api-operator).
```release-note
fix: invalid string for manager's deployment containerPort
```
> fix: invalid string for manager's deployment containerPort

- hack/checkin_account.py
- hack/checkout_account.py
- hack/heartbeat_account.py
/kind other
Improves Boskos logging to better help debug issues
```release-note
NONE
```
> hack: improve boskos scripts logging

- docs/proposals/20221123-managed-kubernetes-in-capg.md
Fixes #
**TODOs**:
```release-note
fix: The subject was incorrectly used in some parts of the document.
```
> fix: The subject was incorrectly used in some parts of the document.

- cloud/services/compute/subnets/reconcile.go
- cloud/services/container/clusters/reconcile.go
- exp/api/v1beta1/gcpmanagedcluster_webhook.go
- test/e2e/config/gcp-ci.yaml
- test/e2e/data/infrastructure-gcp/cluster-template-ci-gke-custom-subnet.yaml
- test/e2e/e2e_gke_test.go
/kind bug
This PR enables the creation of clusters in user-provided subnets.  It also adds validation for user-provided subnets to ensure that at least one subnet is in the same region where the cluster will be created. The user-provided subnets are created in the intended region rather than the default region.
Fixes #896
**TODOs**:
```release-note
Fix bug for the creation of clusters in user-provided subnets …
```
> Fix Cluster Creation in User Provided Subnet

- Makefile
/kind cleanup
Also bump CAPI quickstart to v1.7.0
```release-note
NONE
```
> Also bump CAPI quickstart to v1.7.0

- Makefile
- Tiltfile
- hack/install-cert-manager.sh
/kind support
Bump cert-manager to v1.14.4 to align with CAPI
```release-note
Bump cert-manager to v1.14.4
```
> Bump cert-manager to v1.14.4 to align with CAPI

- Makefile
- cloudbuild-nightly.yaml
/kind support
For nightly builds purpose, this PR adds the `cloudbuild-nightly.yaml` file, that gets invoked by image-builder launched via the configured nightly periodic job (https://github.com/kubernetes/test-infra/pull/32501).
`cloudbuild-nightly.yaml` in turn references the `release-staging-nightly` make target, that performs the image and manifests build and push to the staging bucket/registry.
This approach is mostly copied from CAPA ([1](https://github.com/kubernetes-sigs/cluster-api-provider-aws/blob/63c66352579ef08bd365abd529e1924cde6f0d26/Makefile#L620-L626), [2](https://github.com/kubernetes-sigs/cluster-api-provider-aws/blob/63c66352579ef08bd365abd529e1924cde6f0d26/cloudbuild-nightly.yaml#L1), …
> Add cloudbuild-nightly.yaml + release-staging-nightly target

- test/e2e/config/gcp-ci.yaml
- test/e2e/data/infrastructure-gcp/cluster-template-ci-with-internal-lb.yaml
- test/e2e/e2e_test.go
/kind feature
Adds an e2e test when the internal load balancer is configured. This requires https://github.com/kubernetes-sigs/cluster-api-provider-gcp/pull/1222
**TODOs**:
```release-note
NONE
```
> Add e2e test for internal load balancer

- cloud/services/compute/loadbalancers/reconcile.go
/kind bug
To be consistent with how all the other fields are set, including APIServerAddress, the resource selfLink should be used, not the actual IP address.
**TODOs**:
```release-note
None
```
> Use reference for Internal LB address

- cloud/scope/cluster.go
- cloud/scope/machine.go
- cloud/services/compute/instances/reconcile_test.go
- cloud/services/compute/loadbalancers/reconcile_test.go
/kind bug
The Labels field should be set on Disks and ForwardingRules resources from the machine or cluster `AdditionalLabels` field, similar to how it is set on Instances.
Fixes #1274 
**TODOs**:
```release-note
This fix populates the Disk and ForwardingRules resources' `Labels` field from the machine/cluster `AdditionalLabels` field.
```
> Set Labels on Disks and ForwardingRules resources

- api/v1beta1/gcpcluster_webhook.go
- api/v1beta1/gcpcluster_webhook_test.go
- api/v1beta1/types.go
- cloud/scope/cluster.go
- config/crd/bases/infrastructure.cluster.x-k8s.io_gcpclusters.yaml
- config/crd/bases/infrastructure.cluster.x-k8s.io_gcpclustertemplates.yaml
- config/crd/bases/infrastructure.cluster.x-k8s.io_gcpmanagedclusters.yaml
/kind feature
User can set `GCPCluster.Spec.Network.Mtu` for setting the MTU for the network being created. If nothing is passed the MTU will default to 1440 which is the default set here https://cloud.google.com/vpc/docs/mtu
Fixes #1246
**TODOs**:
```release-note
feat: Add ability to add GCPCluster.Spec.Network.Mtu 
```
> feat: Add ability to specify MTU when creating Network

- cloud/services/compute/loadbalancers/reconcile.go
- cloud/services/compute/loadbalancers/service.go
/kind bug
The ForwardingRules resource requires that the SetLabels() method be used to add the labels after the resource has been created. This resource is different than, for example, Instances or Disks. See Issue #1276 for more information.
Fixes #1276 
This is the comment for `ForwardingRules` in https://github.com/googleapis/google-api-go-client/blame/main/compute/v1/compute-gen.go
```
// Labels: Labels for this resource. These can only be added or modified
// by the setLabels method. 
Labels map[string]string `json:"labels,omitempty"
```
**TODOs**:
```release-note
"NONE"
```
> Use SetLabels() to set ForwardingRules labels

- cloud/services/compute/loadbalancers/reconcile_test.go
- cloud/services/compute/loadbalancers/service.go
Add support for SharedVPC when specifying `spec.loadBalancer.internalLoadBalancer.subnet`
Fixes #1279
**TODOs**:
```release-note
NONE
```
> add sharedvpc support for lb subnet

- cloud/services/container/clusters/reconcile.go
/kind bug
This PR fixes a bug that causes a panic in the reconciler when handling unexported fields in the `compareMasterAuthorizedNetworksConfig` function. The bug occurs when creating a GKE cluster with a master authorized network.
The proposed solution is to ignore the unexported field using `cmpopts.IgnoreUnexported`.
**TODOs**:
```release-note
fix:  compareMasterAuthorizedNetworksConfig avoid panic in reconciler
```
> fix: improve compareMasterAuthorizedNetworksConfig

- cloud/services/compute/loadbalancers/reconcile.go
- cloud/services/compute/loadbalancers/reconcile_test.go
/kind bug
Sets the API port used for the Internal Load Balancer to be the same as that used for the External Load Balancer.
Fixes #1273
**TODOs**:
```release-note
NONE
```
> For internal Load Balancer use the same API port as external LB

- api/v1beta1/gcpmachine_types.go
- config/crd/bases/infrastructure.cluster.x-k8s.io_gcpmachines.yaml
- config/crd/bases/infrastructure.cluster.x-k8s.io_gcpmachinetemplates.yaml
- exp/api/v1beta1/gcpmanagedmachinepool_types.go
/kind api-change
There are missing disk types that are used by downstream services. This PR adds the pd-balanced and hyperdisk-balanced disk types so that others can create machines with these disk types.
**TODOs**:
```release-note
Add the ability to use the pd-balanced and hyperdisk-balanced for the root device type and the addition disks.
```
> Add additional disk types

- api/v1beta1/gcpmachine_types.go
- api/v1beta1/zz_generated.deepcopy.go
- cloud/scope/machine.go
- config/crd/bases/infrastructure.cluster.x-k8s.io_gcpmachines.yaml
- config/crd/bases/infrastructure.cluster.x-k8s.io_gcpmachinetemplates.yaml
- docs/book/src/topics/preemptible-vms.md
/kind feature
Adds support for GCP Spot VMs, which are distinct from `preemptible` vms. Spot VMs are newer.
https://cloud.google.com/compute/docs/instances/spot
They no longer have a mandatory 24 hr limit.
Modeled PR after the [addition of preemptible vms](https://github.com/kubernetes-sigs/cluster-api-provider-gcp/pull/300). 
Documentation that specifies details on `provisioningModel`, `SPOT` and `STANDARD`--
https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/compute_instance#provisioning_model
https://cloud.google.com/compute/docs/instances/create-use-spot#create
Relevant docs about field logic--
```
"provisioningModel": "SPOT" in the Compute Engine API …
```
> Add support for Spot VMs

- CONTRIBUTING.md
- README.md
The `sig-cluster-lifecycle` Google mailing list address has finally been migrated to https://groups.google.com/a/kubernetes.io/g/sig-cluster-lifecycle (you have probably received a number of meeting invites in the last few days) and at some point the old group will be blocked. This PR updates references to the old Google group.
This migration is great for CAPG because we now have an official entry in the calendar for the office hours! You can import it to your personal calendar.
Fixes #1334 
**TODOs**:
```release-note
NONE
```
> chore: update sig-cluster-lifecycle links

- exp/api/v1beta1/gcpmanagedcluster_webhook_test.go
- exp/api/v1beta1/gcpmanagedcontrolplane_webhook_test.go
- exp/api/v1beta1/gcpmanagedmachinepool_webhook_test.go
/kind feature
As we already started discussions on promoting managed clusters out of experimental (refer to [this issue](https://github.com/kubernetes-sigs/cluster-api-provider-gcp/issues/1168)), this PR improves test coverage of control plane, cluster and machine pool webhooks. Some existing machine pool test cases have been formatted to align with the newly added scenarios (which are similar to the ones used by other providers). 
Fixes #
**TODOs**:
```release-note
Improve managed clusters test coverage
```
> Increase test coverage for managed cluster webhooks

- templates/cluster-template.yaml
/kind bug
Related to #1331
Since we did not manage to get cloud-provider _external_ works properly and it's not (yet) removed, I open this PR to (at least) provide a working Out Of the Box user XP when trying to start a Kubernetes 1.29+ cluster with this provider.
I'm not sure that documentation is needed, since it's already documented upstream.
**TODOs**:
```release-note
Disable required feature gates for Kubernetes 1.29+
```
> Support Kubernetes 1.29+

- templates/cluster-template-clusterclass.yaml
- templates/cluster-template-topology.yaml
/kind feature
Add `ClusterClass` and `Topology` cluster templates based on existing E2E infrastructure files. These files will be referenced in the book so users can get started with cluster classes via `clusterctl generate`, similar to the existing documentation on how to create a GKE cluster.
Fixes #
A follow up to this PR will update the book and add references to these new templates.
**TODOs**:
```release-note
NONE
```
> chore: add clusterclass sample template

- docs/book/src/SUMMARY.md
- docs/book/src/developers/e2e.md
- docs/book/src/managed/index.md
/kind cleanup
Follow-up to restructuring the book https://github.com/kubernetes-sigs/cluster-api-provider-gcp/pull/1353, as some links were found to be broken.
Additionally, this adds a new `Developers` section on basic information on how to add a new E2E test case to existing suite.
Fixes #
**TODOs**:
```release-note
NONE
```
> Fix broken book links and add section on adding new E2E tests

- cloud/services/container/nodepools/reconcile.go
- exp/controllers/gcpmanagedmachinepool_controller.go
/kind bug
Controller logs show an error during reconciliation if GCP-controlled automatic updates are currently running on node pools. This is because the error received from Google's API cannot be unwrapped, even if there is logic in the controller code to check for this failure. Same behavior occurs when deleting a cluster but, in this case, there's no existing logic to handle this API response.
This PR returns the error in an *unwrappable* format for update operations and adds the same error validation for deletions.
Fixes #1363 
**TODOs**:
```release-note
Fix controller error on GKE node pool updates
```
> fix: wrap error when nodepool update/delete fails

- cloud/services/container/clusters/reconcile.go
- config/crd/bases/infrastructure.cluster.x-k8s.io_gcpmanagedcontrolplanes.yaml
- exp/api/v1beta1/gcpmanagedcontrolplane_types.go
/kind feature
The goal of this PR is to add identity service support, see https://cloud.google.com/kubernetes-engine/docs/how-to/oidc
This kind of feature enabled use of OIDC
Fixes #
**Special notes for your reviewer**: how can I run test locally?
**TODOs**:
```release-note
Add support for identity service on GKE control plane 
```
> feat: add support for identity service in GCPManagedControlPlane

- Makefile
/kind cleanup
This change adds support for `STAGING_REGISTRY`/`PROD_REGISTRY` and `RELEASE_TAG` overrides in the `Makefile`. The current configuration does not allow setting a different value for these parameters via environment variables. This is a limitation in, for example, an air-gapped environment where a user may want to create their own release of the provider and reference an image stored in a custom registry.
It should not affect any existing use cases as the default value is unchanged.
Fixes #
**TODOs**:
```release-note
NONE
```
> chore: support registry and tag overrides in makefile

- config/crd/patches/webhook_in_gcpclusters.yaml
- config/crd/patches/webhook_in_gcpclustertemplates.yaml
- config/crd/patches/webhook_in_gcpmachines.yaml
- config/crd/patches/webhook_in_gcpmachinetemplates.yaml
What this PR does / why we need it:
Starting with Kubernetes 1.31 it won't be possible anymore to continuously apply CRDs that are setting caBundle to an invalid value (in our case Cg==). The solution is to simply drop the caBundle field (it was never actually required by kube-apiserver).
For more details see: https://kubernetes.slack.com/archives/C0EG7JC6T/p1722441161968339
Let me know if you have any questions.
We'll want to backport this into all supported releases. It's never great to set the caBundle to an invalid value, even before Kubernetes 1.31.
This is an effort driven by CAPI: https://github.com/kubernetes-sigs/cluster-api/pull/10972
> rm caBundle

- api/v1beta1/types.go
- cloud/scope/cluster.go
- cloud/scope/managedcluster.go
- config/crd/bases/infrastructure.cluster.x-k8s.io_gcpclusters.yaml
- config/crd/bases/infrastructure.cluster.x-k8s.io_gcpclustertemplates.yaml
- config/crd/bases/infrastructure.cluster.x-k8s.io_gcpmanagedclusters.yaml
/kind api-change
/kind feature
Adding the ability to enable dual stacks.
Subnets are one of the resources that control the ability to use a dual stack (IPV4
and IPV6). These are required to be set on resource creation, and they cannot be
altered post creation.
The user has the option to set the stack type for each subnet (IPV4_ONLY, IPV4_IPV6, or
IPV6_ONLY). The default will be IPV4_ONLY.
Fixes # https://issues.redhat.com/browse/CORS-3762
_Please confirm that if this PR changes any image versions, then that's the sole change this …
> Enable dual stack

- api/v1beta1/gcpmachine_types.go
- api/v1beta1/gcpmachine_webhook.go
- api/v1beta1/gcpmachine_webhook_test.go
- api/v1beta1/gcpmachinetemplate_webhook_test.go
- cloud/scope/machine.go
- cloud/services/compute/instances/reconcile_test.go
- config/crd/bases/infrastructure.cluster.x-k8s.io_gcpmachines.yaml
- config/crd/bases/infrastructure.cluster.x-k8s.io_gcpmachinetemplates.yaml
/kind feature
Only SEV machines could be configured by using the former
confidentialCompute Enabled/Disabled. GCP allows now to also configure
the confidential instance type as well by using the appropriate
parameter, see [0].
This commit introduces confidentialInstanceType, which lets users choose
between sev or sev-snp as their confidential computing technology of
choice.
Meanwhile, add c3d as a machine that supports AMD SEV.
[0] https://cloud.google.com/confidential-computing/confidential-vm/docs/create-a-confidential-vm-instance#rest
Fixes …
> Support SEV_SNP instance type configuration

- api/v1beta1/gcpmachine_types.go
- config/crd/bases/infrastructure.cluster.x-k8s.io_gcpmachines.yaml
- config/crd/bases/infrastructure.cluster.x-k8s.io_gcpmachinetemplates.yaml
/kind bug
I introduced a typo in the AMD SEV/SEV-SNP confidentialCompute values. It stated "Encryted" instead of "Encrypted".
This patch fixes the typos.
Fixes #
Typo introduced in #1410 @damdo, @JoelSpeed
**TODOs**:
```release-note
NONE
```
> confidentialCompute: Fix "Encryted" typo

- .golangci.yml
- cloud/scope/managedcontrolplane.go
- cloud/services/container/clusters/reconcile.go
- config/crd/bases/infrastructure.cluster.x-k8s.io_gcpmanagedcontrolplanes.yaml
- exp/api/v1beta1/gcpmanagedcontrolplane_types.go
- exp/api/v1beta1/gcpmanagedcontrolplane_webhook.go
- exp/api/v1beta1/gcpmanagedcontrolplane_webhook_test.go
- exp/api/v1beta1/zz_generated.deepcopy.go
- test/e2e/data/infrastructure-gcp/cluster-template-ci-gke.yaml
/kind bug
To align `GCPManagedControlPlane` specification and status with CAPI >=v1.9 we need to introduce new control plane version fields and set existing ones for deprecation in coming releases. The list of changes, as agreed on Slack (thanks @damdo @richardcase @cpanato):
- Introduce new `Version` fields in `GCPManagedControlPlaneSpec` and `GCPManagedControlPlaneStatus` as per the updated CAPI contract for control planes.
- Mark `ControlPlaneVersion` and `CurrentVersion` as deprecated with a message saying to use `Version` instead.
- Have a validation webhook that disallows setting `Version` and `ControlPlaneVersion`.
- Update all templates and e2e tests to use `Version`.
Fixes #1433 
**Special notes for your …
> feat: align GCPManagedControlPlane with CAPI >=v1.9

- cloud/services/container/clusters/reconcile.go
/kind bug
When provisioning GKE clusters I've experienced some panics related to a nil pointer during reconciliation. This small change adds null validation for the specific fields that caused these issues.
Fixes #
**TODOs**:
```release-note
NONE
```
> fix: panic on gke cluster creation

- Tiltfile
The tiltfile was broken (trying to write process.txt).
Sync up with the values in the (main) cluster-api tiltfile.
> chore: update tiltfile for immutable images

- exp/controllers/gcpmanagedcontrolplane_controller.go
/kind bug
Managed control plane controller panics during cluster deletion because, before removing the finalizer, it tries to get the deleting condition. With this PR, it will now check for nil before fetching the condition. 
Fixes #1454 
**TODOs**:
```release-note
Fix panic on GKE cluster deletion
```
> fix: panic on gke cluster deletion

- cloudbuild-nightly.yaml
- cloudbuild.yaml
/kind other
cloudbuild: bump gcb image to get go 1.23
```release-note
NONE
```
> cloudbuild: bump gcb image to get go 1.23

- exp/controllers/gcpmanagedcluster_controller.go
/kind bug
During cluster deletion, a `GCPManagedCluster` may be deleted before its associated `GCPManagedMachinePool`/s which actually needs the cluster resource to exist to delete successfully:
```
E0321 10:41:55.730846       1 controller.go:324] "Reconciler error" err="GCPManagedCluster.infrastructure.cluster.x-k8s.io \"cluster-gke\" not found" controller="gcpmanagedmachinepool" controllerGroup="infrastructure.cluster.x-k8s.io" controllerKind="GCPManagedMachinePool" GCPManagedMachinePool="default/cluster-gke-mp-0" namespace="default" name="cluster-gke-mp-0" reconcileID="5e38a1b8-a006-4c22-973b-a7ebe1ca8c06"
E0321 10:42:05.971755       1 gcpmanagedmachinepool_controller.go:270] "Failed to retrieve GCPManagedCluster from …
```
> fix: make sure machine pools are deleted before gke cluster

- test/e2e/capi_test.go
/kind failing-test
fix: capi-e2e test flavor reference, as the name has changed in https://github.com/kubernetes-sigs/cluster-api-provider-gcp/pull/1355
Context:
`
"failed to read "cluster-template-topology.yaml" from provider's repository "infrastructure-gcp": failed to read file "/logs/artifacts/repository/infrastructure-gcp/v1.10.99/cluster-template-topology.yaml" from local release v1.10.99: stat /logs/artifacts/repository/infrastructure-gcp/v1.10.99/cluster-template-topology.yaml: no such file or directory"
`
https://prow.k8s.io/view/gs/kubernetes-ci-logs/pr-logs/pull/kubernetes-sigs_cluster-api-provider-gcp/1459/pull-cluster-api-provider-gcp-capi-e2e/1918628474663211008
> fix: capi-e2e test flavor reference

- cloud/services/container/clusters/reconcile.go
/kind feature
Allow passing the `Pod.CidrBlock` and `Service.CidrBlock` to GCPManagedControlPlane instances.
Expands #1027 
Supersedes https://github.com/kubernetes-sigs/cluster-api-provider-gcp/pull/1390
**TODOs**:
```release-note
Fix a bug to support `secondyCidrBlocks` for GCPManagedControlPlane instances.
```
> Secondary ranges for GCPManagedControlPlane

- cloud/services/container/clusters/reconcile.go
- config/crd/bases/infrastructure.cluster.x-k8s.io_gcpmanagedcontrolplanes.yaml
- config/crd/bases/infrastructure.cluster.x-k8s.io_gcpmanagedcontrolplanetemplates.yaml
- exp/api/v1beta1/gcpmanagedcontrolplane_types.go
/kind feature
This PR add support for the release channel extended, see:
- https://cloud.google.com/kubernetes-engine/docs/concepts/release-channels#channels 
- https://pkg.go.dev/cloud.google.com/go/container/apiv1/containerpb#ReleaseChannel_EXTENDED
Fixes #
**TODOs**:
```release-note
Add support for release channel extended
```
> feat: add support for extended release channel

- Makefile
The make lint target was broken: go: github.com/golangci/golangci-lint/cmd/golangci-lint@v2.1.6: github.com/golangci/golangci-lint/cmd/golangci-lint@v2.1.6: invalid version: unknown revision cmd/golangci-lint/v2.1.6
```release-note
NONE
```
> chore: cleanup golangci-lint in Makefile

- metadata.yaml
Requirement introduced by https://github.com/kubernetes-sigs/cluster-api/pull/12242
/kind cleanup
```release-note
NONE
```
> chore: add Metadata kind to metadata

- Makefile
- hack/verify-apidiff
We want to check if our public APIs have changed, not if our internal implementation has changed.
Focus only on differences in api/ and exp/api/
```release-note
NONE
```
> chore: make apidiff focus on our APIs

- controllers/gcpcluster_controller_test.go
- controllers/gcpmachine_controller.go
- controllers/gcpmachine_controller_test.go
- exp/controllers/gcpmanagedcontrolplane_controller.go
- exp/controllers/gcpmanagedmachinepool_controller.go
It is deprecated in newer versions of controller-runtime,
because it should not be used.
```release-note
NONE
```
> chore: don't use Requeue in controller-runtime

- cloud/services/container/clusters/reconcile.go
- cloud/services/container/nodepools/reconcile.go
Newer go versions flag this (non-constant used as format message).  As with #1516 we may want to cherry-pick (?), and it makes #1509 smaller
```release-note
chore: fix go vet errors around conditions.MarkFalse
```
(Technically the messages do change, and I could replace it with a "%s" or "%v" if we want the same messages.  I think this is clearer and the message is not part of our contract, but I'm happy to switch to %s if desired)
> chore: fix go vet errors around conditions.MarkFalse

- test/e2e/config/gcp-ci.yaml
Test with kubernetes 1.33, which is notable because it drops support for in-tree cloudprovider.
```release-note
NONE
```
> tests: test with kubernetes 1.33.2

- api/v1beta1/gcpcluster_webhook_test.go
- api/v1beta1/gcpclustertemplate_webhook_test.go
- api/v1beta1/gcpmachine_webhook_test.go
- api/v1beta1/gcpmachinetemplate_webhook_test.go
- exp/api/v1beta1/gcpmanagedcluster_webhook_test.go
- exp/api/v1beta1/gcpmanagedcontrolplane_webhook_test.go
- exp/api/v1beta1/gcpmanagedmachinepool_webhook_test.go
/kind other
Fixes #
**TODOs**:
```release-note
NONE
```
> Replace context.Background() with t.Context()

- api/v1beta1/types.go
- cloud/scope/cluster.go
- cloud/scope/managedcluster.go
- config/crd/bases/infrastructure.cluster.x-k8s.io_gcpclusters.yaml
- config/crd/bases/infrastructure.cluster.x-k8s.io_gcpclustertemplates.yaml
- config/crd/bases/infrastructure.cluster.x-k8s.io_gcpmanagedclusters.yaml
- config/crd/bases/infrastructure.cluster.x-k8s.io_gcpmanagedclustertemplates.yaml
/kind feature
**What this PR does / why we need it**
** This is a regression for the openshift installer.
Instead of filling this value in, the default will be 64 (so that this is backwards compatible), otherwise the user can provide this information in the cluster spec.
** MinPortsPerVM: Minimum number of ports allocated to a VM from this NAT config. If not set, a default number of ports is allocated to a VM. This is rounded up to the nearest power of 2. For example, if the value of this field is 50, at least 64 ports are allocated to a VM.
Fixes #
https://issues.redhat.com/browse/OCPBUGS-61876
**Special …
> Provide a MinPortsPerVM for Nat Router
